export const documentPresets = [
  { name: "Consentimento informado", documentType: "consent", workflowType: "patient_signature", title: "Termo de consentimento informado", content: "Eu, {{cliente}}, declaro que recebi informações claras sobre o procedimento proposto pela {{clinica}}, incluindo objetivos, cuidados, riscos, alternativas e possibilidade de revogar este consentimento antes da realização.\n\nDeclaro que tive oportunidade de esclarecer dúvidas e autorizo a realização do procedimento descrito pela equipe responsável.\n\nData: {{data}}." },
  { name: "Consentimento de uso de imagem", documentType: "consent", workflowType: "patient_signature", title: "Autorização de uso de imagem", content: "Eu, {{cliente}}, autorizo a {{clinica}} a utilizar imagens relacionadas ao atendimento exclusivamente nas finalidades abaixo descritas pela clínica, respeitando minha privacidade e a legislação aplicável.\n\nFinalidade autorizada: [PREENCHER]\nPrazo ou condições: [PREENCHER]\n\nData: {{data}}." },
  { name: "Anamnese geral", documentType: "anamnesis", workflowType: "patient_signature", title: "Ficha de anamnese", content: "Responda com atenção às perguntas apresentadas. Informe alergias, medicamentos em uso, condições de saúde, procedimentos anteriores e qualquer informação relevante para um atendimento seguro.\n\nAs respostas serão anexadas a este documento no momento da assinatura.\n\nData: {{data}}." },
  { name: "Contrato de prestação de serviços", documentType: "contract", workflowType: "patient_signature", title: "Contrato de prestação de serviços", content: "CONTRATADA: {{clinica}}\nCONTRATANTE: {{cliente}}\n\nObjeto, valores, condições, responsabilidades e regras de cancelamento: [PERSONALIZAR ANTES DE USAR].\n\nData: {{data}}." },
  { name: "Receituário simples", documentType: "prescription", workflowType: "professional_issue", title: "Receituário", content: "Paciente: {{cliente}}\n\nUSO: [PREENCHER]\n\n1. [MEDICAMENTO / APRESENTAÇÃO]\nPosologia: [PREENCHER]\nQuantidade: [PREENCHER]\n\nOrientações: [PREENCHER]\n\nData: {{data}}." },
  { name: "Laudo profissional", documentType: "report", workflowType: "professional_issue", title: "Laudo", content: "Paciente: {{cliente}}\n\nFinalidade: [PREENCHER]\n\nHistórico e achados relevantes:\n[PREENCHER]\n\nConclusão:\n[PREENCHER]\n\nData: {{data}}." },
  { name: "Atestado", documentType: "certificate", workflowType: "professional_issue", title: "ATESTADO MÉDICO", content: "Atesto para os devidos fins que o(a) Sr.(a) {{cliente}}, portador(a) do CPF nº [PREENCHER], esteve sob meus cuidados médicos nesta data e necessita de afastamento de suas atividades laborais/escolares por [PREENCHER] ([PREENCHER]) dias, a contar de [PREENCHER], por apresentar incapacidade temporária para o trabalho.\n\nCID: incluir somente com a autorização expressa do paciente.\n\n[PREENCHER], {{data}}." },
  { name: "Declaração de comparecimento", documentType: "declaration", workflowType: "professional_issue", title: "Declaração de comparecimento", content: "Declaro, para os devidos fins, que {{cliente}} compareceu à {{clinica}} em {{data}}, no período de [PREENCHER], para atendimento.\n\nEsta declaração não informa diagnóstico ou condição clínica." },
  { name: "Encaminhamento", documentType: "referral", workflowType: "professional_issue", title: "Encaminhamento", content: "Paciente: {{cliente}}\n\nEncaminho para: [PROFISSIONAL / ESPECIALIDADE]\n\nMotivo e informações pertinentes:\n[PREENCHER]\n\nData: {{data}}." },
  { name: "Solicitação de exame", documentType: "exam_request", workflowType: "professional_issue", title: "Solicitação de exame", content: "Paciente: {{cliente}}\n\nExame(s) solicitado(s):\n[PREENCHER]\n\nIndicação clínica pertinente:\n[PREENCHER]\n\nData: {{data}}." },
] as const;
