import { legalDocumentPresets } from "@/lib/legal-documents";

export const documentPresets = [
  ...legalDocumentPresets,
  { name: "Anamnese geral", documentType: "anamnesis", workflowType: "patient_signature", title: "Ficha de anamnese", content: "Responda com atenção às perguntas apresentadas. Informe alergias, medicamentos em uso, condições de saúde, procedimentos anteriores e qualquer informação relevante para um atendimento seguro.\n\nAs respostas serão anexadas a este documento no momento da assinatura.\n\nData: {{data}}." },
  { name: "Receituário simples", documentType: "prescription", workflowType: "professional_issue", title: "Receituário", content: "Paciente: {{cliente}}\n\nUSO: [PREENCHER]\n\n1. [MEDICAMENTO / APRESENTAÇÃO]\nPosologia: [PREENCHER]\nQuantidade: [PREENCHER]\n\nOrientações: [PREENCHER]\n\nData: {{data}}." },
  { name: "Laudo profissional", documentType: "report", workflowType: "professional_issue", title: "LAUDO", content: "Paciente: {{cliente}}\nClínica: {{clinica}}\nProfissional responsável: {{profissional}}\n\nFINALIDADE DO LAUDO\n[PREENCHER]\n\nHISTÓRICO CLÍNICO E QUEIXA\n[PREENCHER]\n\nAVALIAÇÃO E ACHADOS\n[PREENCHER]\n\nEXAMES E DOCUMENTOS ANALISADOS\n[PREENCHER OU INFORMAR NÃO SE APLICA]\n\nCONCLUSÃO\n[PREENCHER]\n\nRECOMENDAÇÕES\n[PREENCHER OU INFORMAR NÃO SE APLICA]\n\nLocal: [PREENCHER]\nData de emissão: {{data}}." },
  { name: "Declaração acompanhante", documentType: "companion_declaration", workflowType: "professional_issue", title: "DECLARAÇÃO ACOMPANHANTE", content: "Declaro, para os devidos fins, que [NOME COMPLETO DO ACOMPANHANTE], documento de identificação [PREENCHER], acompanhou o(a) paciente {{cliente}} em atendimento na {{clinica}}, no dia [DATA DO ATENDIMENTO], das [HORÁRIO INICIAL] às [HORÁRIO FINAL].\n\nEsta declaração registra a presença do acompanhante durante o período informado.\n\nLocal: [PREENCHER]\nData de emissão: {{data}}.\nProfissional responsável: {{profissional}}." },
  { name: "Atestado", documentType: "certificate", workflowType: "professional_issue", title: "ATESTADO MÉDICO", content: "Atesto para os devidos fins que o(a) Sr.(a) {{cliente}}, portador(a) do CPF nº [PREENCHER], esteve sob meus cuidados médicos nesta data e necessita de afastamento de suas atividades laborais/escolares por [PREENCHER] ([PREENCHER]) dias, a contar de [PREENCHER], por apresentar incapacidade temporária para o trabalho.\n\nCID: incluir somente com a autorização expressa do paciente.\n\n[PREENCHER], {{data}}." },
  { name: "Declaração de comparecimento", documentType: "declaration", workflowType: "professional_issue", title: "Declaração de comparecimento", content: "Declaro, para os devidos fins, que {{cliente}} compareceu à {{clinica}} em {{data}}, no período de [PREENCHER], para atendimento.\n\nEsta declaração não informa diagnóstico ou condição clínica." },
  { name: "Encaminhamento", documentType: "referral", workflowType: "professional_issue", title: "Encaminhamento", content: "Paciente: {{cliente}}\n\nEncaminho para: [PROFISSIONAL / ESPECIALIDADE]\n\nMotivo e informações pertinentes:\n[PREENCHER]\n\nData: {{data}}." },
  { name: "Solicitação de exame", documentType: "exam_request", workflowType: "professional_issue", title: "Solicitação de exame", content: "Paciente: {{cliente}}\n\nExame(s) solicitado(s):\n[PREENCHER]\n\nIndicação clínica pertinente:\n[PREENCHER]\n\nData: {{data}}." },
] as const;
