export type LegalField = { id: string; label: string; type?: "textarea" | "date" | "number" | "money"; required?: boolean; source?: "description" | "preparation" | "price"; defaultValue?: string };
export type LegalDefinition = { key: string; name: string; type: "contract" | "consent" | "term"; procedure: boolean; fields: LegalField[]; content: string };
const f = (id: string, label: string, type: LegalField["type"] = "textarea", source?: LegalField["source"]): LegalField => ({ id, label, type, source, required: true });
const paymentFields = [f("sessions", "Quantidade de sessões", "number"), f("unitPrice", "Valor por sessão (R$)", "money", "price"), f("payment", "Condições de pagamento"), f("startDate", "Início previsto", "date"), f("endDate", "Término previsto", "date")];
export const legalDefinitions: LegalDefinition[] = [
 { key: "contract", name: "Contrato de prestação de serviços", type: "contract", procedure: true, fields: [f("scope", "Serviços e materiais incluídos", "textarea", "description"), ...paymentFields, f("cancellation", "Condições de reagendamento, cancelamento e devolução")], content: "OBJETO\n{{procedimento}}. {{scope}}\nSessões: {{sessions}}. Duração cadastrada por sessão: {{duracao}}.\n\nPREÇO E PAGAMENTO\nValor por sessão: {{unitPrice}}. Total: {{total}}.\n{{payment}}\nPeríodo previsto: {{startDate}} a {{endDate}}. Alterações serão acordadas entre as partes.\n\nEXECUÇÃO E RESPONSABILIDADES\nA clínica realizará o serviço por profissional habilitado, após avaliação individual, prestando os esclarecimentos e cuidados necessários. O paciente fornecerá informações pertinentes ao atendimento e seguirá as orientações recebidas. Os resultados e limitações serão discutidos individualmente, sem promessa de resultado uniforme. O consentimento específico para o procedimento será documentado separadamente.\n\nCANCELAMENTO E REAGENDAMENTO\n{{cancellation}}\nAs condições serão aplicadas respeitando os direitos legais do consumidor, inclusive o direito de arrependimento quando aplicável. Este contrato não afasta a responsabilidade por falhas na prestação do serviço nem limita direitos previstos em lei." },
 { key: "budget", name: "Orçamento e plano de tratamento", type: "contract", procedure: true, fields: [f("scope", "Serviços, materiais e equipamentos incluídos", "textarea", "description"), ...paymentFields, f("validUntil", "Validade do orçamento", "date")], content: "PLANO PROPOSTO\nProcedimento: {{procedimento}}.\n{{scope}}\nQuantidade de sessões: {{sessions}}. Duração cadastrada por sessão: {{duracao}}.\n\nORÇAMENTO\nValor por sessão: {{unitPrice}}. Total: {{total}}.\nCondições de pagamento: {{payment}}\nInício previsto: {{startDate}}. Término previsto: {{endDate}}.\nValidade deste orçamento: {{validUntil}}.\n\nO aceite registra a aprovação do plano e dos valores. Alterações dependerão de nova negociação e registro. O procedimento depende de avaliação e consentimento informado específico. Este documento não comprova pagamento." },
 { key: "consent", name: "Consentimento informado", type: "consent", procedure: true, fields: [f("purpose", "Finalidade e descrição", "textarea", "description"), f("benefits", "Benefícios esperados e limitações"), f("risks", "Riscos, efeitos adversos e contraindicações específicos"), f("alternatives", "Alternativas, incluindo não realizar o procedimento"), f("care", "Cuidados e acompanhamento necessários", "textarea", "preparation")], content: "PROCEDIMENTO\n{{procedimento}}\n{{purpose}}\n\nBENEFÍCIOS E LIMITAÇÕES\n{{benefits}}\n\nRISCOS E CONTRAINDICAÇÕES\n{{risks}}\n\nALTERNATIVAS\n{{alternatives}}\n\nCUIDADOS E ACOMPANHAMENTO\n{{care}}\n\nDeclaro que recebi explicações em linguagem compreensível, tive oportunidade de formular perguntas e obter esclarecimentos e decido livremente autorizar o procedimento acima. Posso retirar meu consentimento, respeitadas as medidas necessárias à continuidade segura dos cuidados. A autorização não inclui divulgação de imagens, que exige manifestação separada, e não representa renúncia a direitos ou exoneração de responsabilidade da clínica ou do profissional." },
 { key: "instructions", name: "Orientações pré e pós-procedimento", type: "term", procedure: true, fields: [f("before", "Cuidados antes do procedimento", "textarea", "preparation"), f("after", "Cuidados após o procedimento"), f("alerts", "Sinais de alerta e quando buscar atendimento"), f("followUp", "Retorno e acompanhamento")], content: "PROCEDIMENTO: {{procedimento}}\n\nANTES DO PROCEDIMENTO\n{{before}}\n\nAPÓS O PROCEDIMENTO\n{{after}}\n\nSINAIS DE ALERTA\n{{alerts}}\n\nRETORNO E ACOMPANHAMENTO\n{{followUp}}\nContato da clínica: {{contato}}.\nConfirmo o recebimento destas orientações e a oportunidade de esclarecer dúvidas. Em situação de urgência, devo procurar assistência imediata; o contato com a clínica não substitui atendimento de emergência." },
 { key: "image", name: "Consentimento de uso de imagem", type: "consent", procedure: false, fields: [f("purpose", "Finalidade da divulgação"), f("channels", "Canais e materiais autorizados"), f("imageScope", "Imagens autorizadas e limites de identificação"), f("validUntil", "Prazo da autorização", "date")], content: "AUTORIZAÇÃO ESPECÍFICA E OPCIONAL\nAutorizo a {{clinica}} a usar exclusivamente as imagens descritas: {{imageScope}}.\nFinalidade: {{purpose}}.\nCanais e materiais: {{channels}}.\nPrazo: até {{validUntil}}.\n\nA decisão é voluntária e não condiciona o atendimento. Posso solicitar a revogação pelo contato {{contato}}. A clínica observará a privacidade e as regras profissionais aplicáveis; a autorização não permite usos proibidos por essas regras. O registro fotográfico para acompanhamento clínico não autoriza, por si só, divulgação pública." },
 { key: "privacy", name: "Aviso de privacidade do paciente", type: "term", procedure: false, fields: [f("purposes", "Finalidades do tratamento de dados"), f("sharing", "Compartilhamentos efetivamente realizados"), f("retention", "Critérios e prazos de conservação"), f("privacyContact", "Canal de privacidade e exercício de direitos")], content: "CONTROLADOR\n{{clinica}}, identificação fiscal {{cnpj}}.\n\nDADOS E FINALIDADES\nSão tratados dados de identificação, contato, contratação e, conforme o atendimento, informações de saúde e registros clínicos.\nFinalidades: {{purposes}}\nO tratamento utilizará a base legal apropriada a cada finalidade, incluindo as hipóteses legais aplicáveis ao atendimento, execução contratual e cumprimento de obrigações. Quando depender de consentimento, ele será solicitado de modo específico e separado.\n\nCOMPARTILHAMENTO\n{{sharing}}\n\nCONSERVAÇÃO\n{{retention}}\n\nDIREITOS E CONTATO\nO titular pode solicitar informações, acesso, correção e os demais direitos previstos na LGPD, observadas as hipóteses legais de conservação e sigilo.\nCanal: {{privacyContact}}.\nA assinatura registra a ciência deste aviso; não representa consentimento genérico para qualquer tratamento de dados." },
 { key: "refusal", name: "Recusa ou retirada de consentimento", type: "term", procedure: true, fields: [f("decision", "Procedimento ou conduta recusada e decisão do paciente"), f("explanations", "Esclarecimentos e consequências discutidos"), f("continuity", "Alternativas e plano de continuidade dos cuidados")], content: "PROCEDIMENTO: {{procedimento}}\n\nDECISÃO\n{{decision}}\n\nESCLARECIMENTOS\n{{explanations}}\n\nCONTINUIDADE DOS CUIDADOS\n{{continuity}}\n\nRegistro minha decisão livre após oportunidade de esclarecer dúvidas. Este registro não implica renúncia a direitos, não exonera a clínica ou o profissional de suas responsabilidades e não autoriza represálias ou interrupção insegura dos cuidados." },
 { key: "termination", name: "Distrato e acerto financeiro", type: "contract", procedure: true, fields: [f("reference", "Contrato original e motivo do encerramento"), f("performed", "Sessões e serviços efetivamente realizados"), f("paid", "Valor já pago (R$)", "money"), f("balance", "Acerto: valores a devolver ou pagar e memória de cálculo"), f("deadline", "Prazo para o acerto", "date"), f("continuity", "Obrigações restantes e continuidade dos cuidados")], content: "ENCERRAMENTO\n{{reference}}\nProcedimento: {{procedimento}}.\nServiços realizados: {{performed}}\n\nACERTO FINANCEIRO\nValor já pago: {{paid}}.\n{{balance}}\nPrazo: {{deadline}}.\n\nOBRIGAÇÕES RESTANTES\n{{continuity}}\n\nO encerramento e os valores acima são registrados de comum acordo, respeitados os direitos legais das partes. Não há quitação de valores ainda não pagos nem renúncia genérica a direitos ou a responsabilidades relacionadas ao atendimento." },
 { key: "guardian", name: "Autorização do responsável legal", type: "consent", procedure: true, fields: [f("guardianName", "Nome completo do responsável", undefined), f("guardianDocument", "CPF ou documento do responsável", undefined), f("relationship", "Vínculo e fundamento da representação"), f("scope", "Atendimento autorizado e esclarecimentos recebidos", "textarea", "description")], content: "RESPONSÁVEL LEGAL\n{{guardianName}}, documento {{guardianDocument}}.\nVínculo e fundamento da representação: {{relationship}}.\n\nPACIENTE E ATENDIMENTO\nPaciente: {{cliente}}. Procedimento: {{procedimento}}.\n{{scope}}\n\nDeclaro possuir poderes para a representação indicada e autorizo o atendimento descrito após os esclarecimentos necessários. O consentimento específico do procedimento será documentado separadamente, com participação do paciente conforme sua capacidade e as regras aplicáveis. Esta autorização não dispensa a conferência da representação legal pela clínica." },
];
export function legalKey(schema: unknown): string | null {
 if (!Array.isArray(schema)) return null;
 const meta = schema.find(item => item && typeof item === "object" && item.kind === "legal_document");
 return meta && legalDefinitions.some(item => item.key === meta.key) ? meta.key : null;
}
export function legalPresetContent(definition: LegalDefinition) {
 return "Clínica: {{clinica}}\nIdentificação fiscal: {{cnpj}}\nEndereço: {{endereco_clinica}}\nPaciente: {{cliente}}\nCPF: {{cpf}}\nEndereço do paciente: {{endereco_cliente}}\nProfissional: {{profissional}}\nRegistro profissional: {{registro}}\nData: {{data}}\n\n" + definition.content;
}
export const legalDocumentPresets = legalDefinitions.map(definition => ({ name: definition.name, title: definition.name, documentType: definition.type, workflowType: "patient_signature", content: legalPresetContent(definition), responseSchema: [{ kind: "legal_document", key: definition.key, version: 1 }] }));
export function renderLegalDocument(content: string, values: Record<string, string>) {
 return content.replace(/{{\s*([\w_]+)\s*}}/g, (_match, key: string) => values[key] || "Não informado");
}
export function legalFieldValues(definition: LegalDefinition, input: Record<string, string>) {
 const values: Record<string, string> = {};
 for (const field of definition.fields) {
 const value = (input[field.id] ?? "").trim();
 if (value.length > 5000 || /\{\{|\[PREENCHER/i.test(value)) throw new Error(`Revise o campo ${field.label}.`);
 if (field.required && !value) throw new Error(`Preencha ${field.label}.`);
 if (field.type === "date" && (!/^\d{4}-\d{2}-\d{2}$/.test(value) || Number.isNaN(Date.parse(value)) || new Date(value + "T12:00:00Z").toISOString().slice(0, 10) !== value)) throw new Error(`Informe uma data válida em ${field.label}.`);
 if (field.type === "number" && (!/^\d+$/.test(value) || Number(value) < 1 || Number(value) > 1000)) throw new Error(`Informe uma quantidade válida em ${field.label}.`);
 if (field.type === "money" && (!/^\d+(\.\d{1,2})?$/.test(value) || Number(value) > 10000000)) throw new Error(`Informe um valor válido em ${field.label}.`);
 values[field.id] = field.type === "date" ? value.split("-").reverse().join("/") : field.type === "money" ? Number(value).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }) : value;
 }
 if (input.startDate && input.endDate && input.endDate < input.startDate) throw new Error("O término deve ser posterior ou igual ao início.");
 if (input.sessions && input.unitPrice) values.total = (Math.round(Number(input.unitPrice) * 100) * Number(input.sessions) / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
 return values;
}

export type LegalClient = { id: string; name: string; cpf: string | null; address: string | null; email: string | null; phone: string | null };
export type LegalProfessional = { id: string; name: string; registration: string };
export type LegalService = { id: string; name: string; description: string | null; preparation: string | null; durationMinutes: number; priceInCents: number | null };
export type LegalOrganization = { name: string; legalName: string | null; taxId: string | null; publicAddress: string | null; phone: string | null; publicEmail: string | null };
export function legalContextValues(organization: LegalOrganization, client: LegalClient, professional: LegalProfessional | undefined, service: LegalService | undefined, date: string) {
 return { clinica: organization.legalName || organization.name, cnpj: organization.taxId || "Não informado", endereco_clinica: organization.publicAddress || "Não informado", cliente: client.name, cpf: client.cpf || "Não informado", endereco_cliente: client.address || "Não informado", profissional: professional?.name || "Não se aplica", registro: professional?.registration || "Não informado", procedimento: service?.name || "Não se aplica", duracao: service ? `${service.durationMinutes} minutos` : "Não se aplica", contato: [organization.phone, organization.publicEmail].filter(Boolean).join(" / ") || "Não informado", data: date };
}

export function reusableLegalFields(definition: LegalDefinition, input: Record<string, unknown>) {
 const reusable = new Set(["scope", "payment", "cancellation", "purpose", "benefits", "risks", "alternatives", "care", "before", "after", "alerts", "followUp", "channels", "imageScope", "purposes", "sharing", "retention", "privacyContact"]);
 const defaults: Record<string, string> = {};
 for (const field of definition.fields.filter(item => reusable.has(item.id))) {
   const value = String(input[field.id] ?? "").trim();
   if (value.length > 5000) throw new Error("Um campo excede o limite permitido.");
   defaults[field.id] = value;
 }
 return defaults;
}
