"use server";
import { and, eq, sql } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { db } from "@/db";
import { inventoryMovements, inventoryProducts, serviceInventoryItems, services } from "@/db/schema";
import { writeAuditLog } from "@/lib/audit";
import { assertOrganizationPermission } from "@/lib/permissions";
import { requireOrganization } from "@/lib/session";
const text = (data: FormData, key: string) => String(data.get(key) ?? "").trim();
const quantity = (data: FormData, key: string) => { const parsed = Number(text(data, key).replace(",", ".")); if (!Number.isFinite(parsed) || parsed < 0) throw new Error("Informe uma quantidade válida."); return Math.round(parsed * 1000); };
const money = (data: FormData, key: string) => { const raw = text(data, key); if (!raw) return null; const parsed = Number(raw.replace(/\./g, "").replace(",", ".")); if (!Number.isFinite(parsed) || parsed < 0) throw new Error("Informe um custo válido."); return Math.round(parsed * 100); };
export async function createInventoryProduct(data: FormData) { const { session, organization } = await requireOrganization(); assertOrganizationPermission(organization.role, "inventory.manage"); const name = text(data, "name"); if (name.length < 2) throw new Error("Informe o nome do produto."); const initial = quantity(data, "initialQuantity"); const [product] = await db.transaction(async (tx) => { const created = await tx.insert(inventoryProducts).values({ organizationId: organization.id, name, sku: text(data, "sku") || null, unit: text(data, "unit") || "unit", currentQuantityMillis: initial, minimumQuantityMillis: quantity(data, "minimumQuantity"), costInCents: money(data, "cost") }).returning({ id: inventoryProducts.id }); if (initial) await tx.insert(inventoryMovements).values({ organizationId: organization.id, productId: created[0].id, type: "initial", quantityMillis: initial, balanceAfterMillis: initial, createdByUserId: session.user.id }); return created; }); await writeAuditLog({ organizationId: organization.id, userId: session.user.id, action: "create", entityType: "inventory_product", entityId: product.id }); revalidatePath("/estoque"); }
export async function moveInventory(data: FormData) { const { session, organization } = await requireOrganization(); assertOrganizationPermission(organization.role, "inventory.manage"); const productId = text(data, "productId"); const type = text(data, "type"); const entered = quantity(data, "quantity"); if (!entered || !["entry", "adjustment_add", "adjustment_remove", "loss"].includes(type)) throw new Error("Informe tipo e quantidade."); await db.transaction(async (tx) => { await tx.execute(sql`select id from inventory_products where id = ${productId} for update`); const [product] = await tx.select().from(inventoryProducts).where(and(eq(inventoryProducts.id, productId), eq(inventoryProducts.organizationId, organization.id))).limit(1); if (!product) throw new Error("Produto não encontrado."); const delta = ["adjustment_remove", "loss"].includes(type) ? -entered : entered; const balance = product.currentQuantityMillis + delta; if (balance < 0) throw new Error("A movimentação deixaria o estoque negativo."); await tx.update(inventoryProducts).set({ currentQuantityMillis: balance, updatedAt: new Date() }).where(eq(inventoryProducts.id, productId)); await tx.insert(inventoryMovements).values({ organizationId: organization.id, productId, type, quantityMillis: delta, balanceAfterMillis: balance, notes: text(data, "notes") || null, createdByUserId: session.user.id }); }); revalidatePath("/estoque"); }
export async function setServiceInventoryItem(data: FormData) { const { organization } = await requireOrganization(); assertOrganizationPermission(organization.role, "inventory.manage"); const serviceId = text(data, "serviceId"); const productId = text(data, "productId"); const amount = quantity(data, "quantity"); const [service, product] = await Promise.all([db.select({ id: services.id }).from(services).where(and(eq(services.id, serviceId), eq(services.organizationId, organization.id))).limit(1), db.select({ id: inventoryProducts.id }).from(inventoryProducts).where(and(eq(inventoryProducts.id, productId), eq(inventoryProducts.organizationId, organization.id))).limit(1)]); if (!service.length || !product.length || !amount) throw new Error("Serviço, produto ou quantidade inválida."); await db.insert(serviceInventoryItems).values({ organizationId: organization.id, serviceId, productId, quantityMillis: amount }).onConflictDoUpdate({ target: [serviceInventoryItems.serviceId, serviceInventoryItems.productId], set: { quantityMillis: amount } }); revalidatePath("/estoque"); }
export async function removeServiceInventoryItem(data: FormData) { const { organization } = await requireOrganization(); assertOrganizationPermission(organization.role, "inventory.manage"); await db.delete(serviceInventoryItems).where(and(eq(serviceInventoryItems.organizationId, organization.id), eq(serviceInventoryItems.serviceId, text(data, "serviceId")), eq(serviceInventoryItems.productId, text(data, "productId")))); revalidatePath("/estoque"); }
