import { and, count, desc, eq, gte } from "drizzle-orm";
import Link from "next/link";

import { diagnoseNfseCompatibility, registerFiscalDocument, requestNfseActivation, saveNfseFiscalProfile } from "@/actions/financial-operations";
import { ActionForm } from "@/components/action-form";
import { PageHeader } from "@/components/page-header";
import { db } from "@/db";
import { financialEntries, fiscalDocuments, organizationFinancialIntegrations } from "@/db/schema";
import { organizationDate } from "@/lib/appointment-safety";
import { readNfseProfile } from "@/lib/nfse-routing";
import { getOrganizationServicePlan, nfsePublicOffer } from "@/lib/service-plans";
import { requireOrganization } from "@/lib/session";

export const metadata = { title: "Emissão de NFS-e" };
const money = (value: number) => (value / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

export default async function NfsePage({ searchParams }: { searchParams: Promise<{ mes?: string }> }) {
  const { organization } = await requireOrganization();
  const query = await searchParams;
  const current = organizationDate(new Date(), organization.timezone).slice(0, 7);
  const month = /^\d{4}-\d{2}$/.test(query.mes ?? "") ? query.mes! : current;
  const monthStart = new Date(`${month}-01T00:00:00-03:00`);
  const [integrations, documents, pendingEntries, [nfseUsage], servicePlan] = await Promise.all([
    db.select({ provider: organizationFinancialIntegrations.provider, environment: organizationFinancialIntegrations.environment, status: organizationFinancialIntegrations.status, metadata: organizationFinancialIntegrations.metadata }).from(organizationFinancialIntegrations).where(eq(organizationFinancialIntegrations.organizationId, organization.id)),
    db.select().from(fiscalDocuments).where(eq(fiscalDocuments.organizationId, organization.id)).orderBy(desc(fiscalDocuments.createdAt)).limit(20),
    db.select({ id: financialEntries.id, description: financialEntries.description }).from(financialEntries).where(and(eq(financialEntries.organizationId, organization.id), eq(financialEntries.status, "pending"))).orderBy(desc(financialEntries.dueDate)).limit(100),
    db.select({ value: count() }).from(fiscalDocuments).where(and(eq(fiscalDocuments.organizationId, organization.id), gte(fiscalDocuments.createdAt, monthStart))),
    getOrganizationServicePlan(organization.id),
  ]);
  const nfseIntegration = integrations.find((item) => item.provider === "nfse");
  const nfseProfile = readNfseProfile(nfseIntegration?.metadata);
  const nfseRequested = nfseIntegration?.status === "requested";
  const nfseReady = nfseIntegration?.status === "active" && Boolean(nfseProfile);
  const needsFiscalProfile = nfseRequested || (Boolean(nfseIntegration) && !nfseProfile);
  const nfseMonthlyLimit = servicePlan.nfseMonthlyLimit || nfsePublicOffer.monthlyLimit;
  const nfseMonthlyPrice = servicePlan.nfseMonthlyPriceInCents || nfsePublicOffer.monthlyPriceInCents;
  const nfseOverage = servicePlan.nfseOverageInCents || nfsePublicOffer.overageInCents;

  return <div className="page-wrap">
    <Link className="mb-4 inline-flex text-sm font-bold text-brand" href={`/financeiro?mes=${month}`}>← Voltar ao fluxo de caixa</Link>
    <PageHeader eyebrow="Financeiro" title="Emissão de NFS-e" description="Ative o serviço, cadastre os dados fiscais e acompanhe a rota de emissão em uma área dedicada." />
    <article className="panel">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-extrabold">Emissor NFS-e Aggenda</h2><p className="mt-1 text-sm text-muted">Emissão pelo Governo sempre que compatível, com fallback pelo parceiro fiscal quando necessário.</p></div><span className="status-pill">{nfseReady ? "Ativo" : nfseProfile ? "Diagnóstico pendente" : nfseRequested ? "Configuração pendente" : "Não contratado"}</span></div>
      {!nfseIntegration && <div className="mt-5 rounded-2xl border border-brand/20 bg-brand/5 p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-extrabold">Plano de emissão</p><p className="mt-1 text-sm leading-6 text-muted">Rota fiscal selecionada automaticamente para reduzir custo e complexidade.</p></div><p className="text-2xl font-extrabold text-brand">{money(nfsePublicOffer.monthlyPriceInCents)}<span className="text-sm font-medium text-muted">/mês</span></p></div><div className="mt-4 grid gap-3 rounded-xl border bg-white p-4 text-sm sm:grid-cols-2"><p><strong>{nfsePublicOffer.monthlyLimit} emissões/mês</strong><br /><span className="text-muted">1 CNPJ · sem acúmulo</span></p><p><strong>{money(nfsePublicOffer.overageInCents)} por excedente</strong><br /><span className="text-muted">XML, DANFSe, consulta e cancelamento</span></p><p><strong>Autoconfiguração gratuita</strong><br /><span className="text-muted">Certificado A1 fornecido pelo cliente</span></p><p><strong>Configuração assistida: {money(nfsePublicOffer.assistedSetupInCents)}</strong><br /><span className="text-muted">Cobrança única, se escolhida</span></p></div><p className="mt-3 text-xs text-muted">Disponibilidade confirmada após diagnóstico do município. Integrações extraordinárias exigem orçamento prévio.</p><ActionForm action={requestNfseActivation} successMessage="Solicitação de NFS-e recebida." className="mt-4 grid gap-3"><label className="grid gap-2 text-sm font-bold">Implantação<select className="field" name="setupMode" defaultValue="self_service"><option value="self_service">Autoconfiguração · grátis</option><option value="assisted">Configuração assistida · {money(nfsePublicOffer.assistedSetupInCents)}</option></select></label><label className="flex items-start gap-3 rounded-xl border bg-white p-3 text-sm"><input className="mt-1" name="acceptNfseOffer" type="checkbox" required /><span>Li e aceito a mensalidade, franquia e valor excedente apresentados. A cobrança em produção será confirmada antes da ativação.</span></label><button className="primary-button">Solicitar ativação da NFS-e</button></ActionForm></div>}
      {needsFiscalProfile && <div className="mt-5"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm"><p className="font-extrabold text-amber-900">Solicitação recebida</p><p className="mt-1 leading-6 text-amber-800">Cadastre os dados fiscais e o certificado A1 para verificarmos a melhor rota.</p></div><ActionForm action={saveNfseFiscalProfile} successMessage="Cadastro fiscal salvo com segurança." className="mt-4 grid gap-3 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold">CNPJ<input className="field" name="cnpj" inputMode="numeric" required placeholder="00.000.000/0000-00" /></label><label className="grid gap-2 text-sm font-bold">Inscrição municipal<input className="field" name="municipalRegistration" required /></label><label className="grid gap-2 text-sm font-bold">Código IBGE do município<input className="field" name="municipalityCode" inputMode="numeric" required minLength={7} maxLength={7} placeholder="Ex.: 2927408" /><span className="text-xs font-normal text-muted">Código de 7 dígitos, não o CEP.</span></label><label className="grid gap-2 text-sm font-bold">Regime tributário<select className="field" name="taxRegime" required><option value="simples_nacional">Simples Nacional</option><option value="mei">MEI</option><option value="lucro_presumido">Lucro Presumido</option><option value="lucro_real">Lucro Real</option></select></label><label className="grid gap-2 text-sm font-bold">Ambiente<select className="field" name="environment" defaultValue="sandbox"><option value="sandbox">Homologação (testes)</option><option value="production">Produção</option></select></label><label className="grid gap-2 text-sm font-bold">Certificado digital A1<input className="field" name="certificate" type="file" accept=".pfx,.p12,application/x-pkcs12" required /></label><label className="grid gap-2 text-sm font-bold md:col-span-2">Senha do certificado<input className="field" name="certificatePassword" type="password" required autoComplete="off" /></label><label className="flex items-start gap-3 rounded-xl border p-3 text-sm md:col-span-2"><input className="mt-1" name="partnerFallbackAuthorized" type="checkbox" /><span><strong>Autorizar fallback automático</strong><span className="block text-muted">Se o município não aceitar a API nacional, o Aggenda poderá utilizar o parceiro fiscal.</span></span></label><button className="primary-button md:col-span-2">Salvar cadastro fiscal</button></ActionForm></div>}
      {nfseProfile && !nfseReady && <div className="mt-5"><div className="rounded-2xl border p-4 text-sm"><p className="font-extrabold">Cadastro fiscal concluído</p><p className="mt-1 text-muted">Município IBGE {nfseProfile.municipalityCode} · CNPJ final {nfseProfile.cnpj.slice(-4)} · {nfseIntegration?.environment === "production" ? "produção" : "homologação"}</p>{nfseProfile.compatibilityMessage && <p className="mt-2 font-medium">{nfseProfile.compatibilityMessage}</p>}</div><ActionForm action={diagnoseNfseCompatibility} successMessage="Compatibilidade fiscal verificada." className="mt-4"><button className="primary-button">Verificar compatibilidade e definir rota</button></ActionForm></div>}
      {nfseReady && <div className="mt-4 grid gap-3 rounded-2xl border p-4 text-sm sm:grid-cols-3"><p><span className="text-muted">Mensalidade</span><strong className="block text-lg">{money(nfseMonthlyPrice)}</strong></p><p><span className="text-muted">Uso em {month}</span><strong className="block text-lg">{nfseUsage?.value ?? 0} de {nfseMonthlyLimit}</strong></p><p><span className="text-muted">Excedente</span><strong className="block text-lg">{money(nfseOverage)}/nota</strong></p></div>}
      {nfseReady && nfseProfile && <div className="mt-5"><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm"><p className="font-extrabold text-emerald-900">Rota fiscal ativa: {nfseProfile.routingMode === "government" ? "Emissor Público Nacional" : "parceiro fiscal"}</p><p className="mt-1 text-emerald-800">Ambiente: {nfseIntegration?.environment === "production" ? "produção" : "homologação"}.</p></div><div className="mt-5 rounded-2xl border p-4"><p className="font-extrabold">Registro de contingência</p><p className="mt-1 text-sm text-muted">Registre uma nota emitida fora do sistema durante a homologação.</p><ActionForm action={registerFiscalDocument} successMessage="Documento fiscal registrado." className="mt-4 grid gap-3"><label className="grid gap-2 text-sm font-bold">Lançamento financeiro<select className="field" name="financialEntryId"><option value="">Sem lançamento vinculado</option>{pendingEntries.map((entry) => <option key={entry.id} value={entry.id}>{entry.description}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Número da NFS-e<input className="field" name="number" placeholder="Ex.: 000123" /></label><label className="grid gap-2 text-sm font-bold">Valor da nota<input className="field" name="amount" inputMode="decimal" required placeholder="Ex.: 250,00" /></label><label className="grid gap-2 text-sm font-bold">Link de verificação<input className="field" name="verificationUrl" type="url" placeholder="https://..." /></label><button className="secondary-button">Registrar NFS-e já emitida</button></ActionForm></div><p className="mt-3 text-xs text-muted">{documents.length} documento(s) fiscal(is) registrado(s).</p></div>}
    </article>
  </div>;
}
