import Image from "next/image";
import Link from "next/link";
import { and, asc, desc, eq } from "drizzle-orm";
import { AlertTriangle, CheckCircle2, CreditCard, RefreshCcw, WalletCards } from "lucide-react";
import { cancelPaymentCharge, connectAsaasAccount, disconnectAsaasAccount, refundPaymentCharge, sendPaymentChargeWhatsApp, testAsaasIntegration, updatePaymentCharge } from "@/actions/payment-charges";
import { connectMercadoPagoAccount, disconnectMercadoPagoAccount, testMercadoPagoIntegration } from "@/actions/mercado-pago";
import { ActionForm } from "@/components/action-form";
import { ChargeCreateForm } from "@/components/charge-create-form";
import { CopyButton } from "@/components/copy-button";
import { PageHeader } from "@/components/page-header";
import { PaymentProviderTabs } from "@/components/payment-provider-tabs";
import { db } from "@/db";
import { clients, financialEntries, organizationFinancialIntegrations, paymentChargeEvents, paymentCharges } from "@/db/schema";
import { organizationDate } from "@/lib/appointment-safety";
import { hasOrganizationPermission } from "@/lib/permissions";
import { requireOrganization } from "@/lib/session";

export const metadata = { title: "Pagamentos" };
const money = (value: number) => (value / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const date = (value: string) => new Date(`${value}T12:00:00Z`).toLocaleDateString("pt-BR");
const statusLabels: Record<string, string> = { pending: "Pendente", paid: "Pago", overdue: "Vencido", cancelled: "Cancelado", refunded: "Estornado" };
const eventLabels: Record<string, string> = { charge_created: "Cobrança emitida", charge_updated: "Cobrança alterada", charge_cancelled: "Cobrança cancelada", refund_requested: "Estorno solicitado", whatsapp_queued: "Envio por WhatsApp enfileirado", PAYMENT_CREATED: "Criada no Asaas", PAYMENT_UPDATED: "Atualizada pelo Asaas", PAYMENT_RECEIVED: "Pagamento recebido", PAYMENT_CONFIRMED: "Pagamento confirmado", PAYMENT_OVERDUE: "Vencimento informado", PAYMENT_DELETED: "Cancelamento confirmado", PAYMENT_REFUNDED: "Estorno confirmado", PAYMENT_PARTIALLY_REFUNDED: "Estorno parcial confirmado" };

export default async function ChargesPage({ searchParams }: { searchParams: Promise<{ busca?: string; status?: string; meio?: string; inicio?: string; fim?: string; pagina?: string }> }) {
  const { organization } = await requireOrganization(); const query = await searchParams; const today = organizationDate(new Date(), organization.timezone); const canManage = hasOrganizationPermission(organization.role, "finance.manage");
  const [allCharges, events, integrationRows, pendingEntries] = await Promise.all([
    db.select().from(paymentCharges).where(eq(paymentCharges.organizationId, organization.id)).orderBy(desc(paymentCharges.createdAt)),
    db.select().from(paymentChargeEvents).where(eq(paymentChargeEvents.organizationId, organization.id)).orderBy(desc(paymentChargeEvents.createdAt)),
    db.select().from(organizationFinancialIntegrations).where(eq(organizationFinancialIntegrations.organizationId, organization.id)),
    db.select({ id: financialEntries.id, description: financialEntries.description, amountInCents: financialEntries.amountInCents, dueDate: financialEntries.dueDate, clientName: clients.name, clientEmail: clients.email, clientPhone: clients.phone }).from(financialEntries).leftJoin(clients, eq(clients.id, financialEntries.clientId)).where(and(eq(financialEntries.organizationId, organization.id), eq(financialEntries.type, "receivable"), eq(financialEntries.status, "pending"))).orderBy(asc(financialEntries.dueDate)),
  ]);
  const activeEntryIds = new Set(allCharges.filter((item) => ["pending", "overdue"].includes(item.status) && item.financialEntryId).map((item) => item.financialEntryId));
  const normalizedSearch = query.busca?.trim().toLocaleLowerCase("pt-BR") ?? "";
  const filtered = allCharges.filter((item) => (!normalizedSearch || `${item.customerName} ${item.description} ${item.customerDocument ?? ""}`.toLocaleLowerCase("pt-BR").includes(normalizedSearch)) && (!query.status || query.status === "all" || item.status === query.status) && (!query.meio || query.meio === "all" || item.paymentMethod === query.meio) && (!query.inicio || item.dueDate >= query.inicio) && (!query.fim || item.dueDate <= query.fim));
  const pageSize = 20; const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const currentPage = Math.min(pages, Math.max(1, Number(query.pagina) || 1)); const charges = filtered.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  const paid = allCharges.filter((item) => item.status === "paid"); const overdue = allCharges.filter((item) => item.status === "overdue" || (item.status === "pending" && item.dueDate < today)); const open = allCharges.filter((item) => ["pending", "overdue"].includes(item.status));
  const integration = integrationRows.find((item) => item.provider === "asaas"); const metadata = (integration?.metadata ?? {}) as Record<string, unknown>; const webhookStatus = String(metadata.webhookStatus ?? "não configurado");
  const mercadoPago = integrationRows.find((item) => item.provider === "mercado_pago"); const mercadoPagoMetadata = (mercadoPago?.metadata ?? {}) as Record<string, unknown>;
  const params = new URLSearchParams(Object.entries(query).filter(([key, value]) => key !== "pagina" && Boolean(value)).map(([key, value]) => [key, String(value)]));

  return <div className="page-wrap"><div className="mb-4"><Link className="text-sm font-bold text-brand" href="/financeiro">← Fluxo de caixa</Link></div><PageHeader eyebrow="Financeiro" title="Pagamentos" description="Emissão, compartilhamento, acompanhamento, inadimplência e conciliação automática em um único lugar." />
    <section className="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article className="panel"><WalletCards className="size-5 text-brand" /><p className="mt-3 text-sm text-muted">Em aberto</p><p className="text-2xl font-extrabold">{money(open.reduce((sum, item) => sum + item.amountInCents, 0))}</p><p className="text-xs text-muted">{open.length} cobrança(s)</p></article><article className="panel"><CheckCircle2 className="size-5 text-emerald-600" /><p className="mt-3 text-sm text-muted">Recebido</p><p className="text-2xl font-extrabold text-emerald-700">{money(paid.reduce((sum, item) => sum + item.amountInCents, 0))}</p><p className="text-xs text-muted">{paid.length} pagamento(s)</p></article><article className="panel"><AlertTriangle className="size-5 text-red-600" /><p className="mt-3 text-sm text-muted">Inadimplência</p><p className="text-2xl font-extrabold text-red-700">{money(overdue.reduce((sum, item) => sum + item.amountInCents, 0))}</p><p className="text-xs text-muted">{overdue.length} vencida(s)</p></article><article className="panel"><CreditCard className="size-5 text-brand" /><p className="mt-3 text-sm text-muted">Conversão</p><p className="text-2xl font-extrabold">{allCharges.length ? `${Math.round((paid.length / allCharges.length) * 100)}%` : "—"}</p><p className="text-xs text-muted">pagas sobre emitidas</p></article></section>

    <PaymentProviderTabs
      defaultTab={integration?.status === "active" ? "asaas" : mercadoPago?.status === "active" ? "mercado-pago" : "asaas"}
      tabs={[
        {
          id: "asaas", label: "Asaas", connected: integration?.status === "active" && webhookStatus === "active", content: <div><div><h2 className="font-extrabold">Conta Asaas</h2><p className="text-sm text-muted">{String(metadata.accountName ?? "Conta ainda não identificada")} · {integration?.environment === "production" ? "Produção" : "Testes"} · webhook {webhookStatus}</p><p className="mt-1 text-xs text-muted">Último teste: {metadata.testedAt ? new Date(String(metadata.testedAt)).toLocaleString("pt-BR") : "não executado"}{metadata.webhookError ? ` · ${String(metadata.webhookError)}` : ""}</p></div><div className="mt-5 border-t pt-5"><p className="text-sm text-muted">Conecte a conta Asaas da própria empresa. A chave é validada e armazenada de forma criptografada; tarifas e recebimentos permanecem sob responsabilidade do titular.</p><ol className="mt-4 grid gap-2 rounded-2xl bg-slate-50 p-4 text-sm"><li><strong>1.</strong> No Asaas, abra Integrações → Chaves de API.</li><li><strong>2.</strong> Copie uma chave do ambiente escolhido.</li><li><strong>3.</strong> O Aggenda valida a conta e configura o webhook automaticamente.</li></ol><ActionForm action={connectAsaasAccount} successMessage="Conta Asaas validada e conectada." className="mt-4 grid gap-3 sm:grid-cols-2"><select className="field" name="environment" defaultValue={integration?.environment === "production" ? "production" : "sandbox"}><option value="sandbox">Testes</option><option value="production">Produção</option></select><input className="field" name="credential" type="password" required autoComplete="off" placeholder="Chave API da conta Asaas" /><button className="primary-button sm:w-fit">Conectar, validar e configurar</button></ActionForm>{integration && <ActionForm action={testAsaasIntegration} successMessage="Conexão validada." className="mt-3"><button className="secondary-button"><RefreshCcw className="mr-2 size-4" />Testar conexão atual</button></ActionForm>}</div></div>,
        },
        {
          id: "mercado-pago", label: "Mercado Pago", connected: mercadoPago?.status === "active", content: <div><div><h2 className="font-extrabold">Conta Mercado Pago</h2><p className="text-sm text-muted">{String(mercadoPagoMetadata.accountName ?? "Conta ainda não conectada")} · {mercadoPago?.environment === "production" ? "Produção" : "Testes"} · webhook {String(mercadoPagoMetadata.webhookStatus ?? "pendente")}</p><p className="mt-1 text-xs text-muted">Último teste: {mercadoPagoMetadata.testedAt ? new Date(String(mercadoPagoMetadata.testedAt)).toLocaleString("pt-BR") : "não executado"}</p></div><div className="mt-5 border-t pt-5"><p className="text-sm text-muted">Use as credenciais da aplicação Mercado Pago da própria empresa. O Checkout Pro oferece Pix, boleto e cartão em ambiente hospedado pelo Mercado Pago.</p><ActionForm action={connectMercadoPagoAccount} successMessage="Conta Mercado Pago validada e conectada." className="mt-4 grid gap-3 sm:grid-cols-2"><select className="field" name="environment" defaultValue={mercadoPago?.environment === "production" ? "production" : "sandbox"}><option value="sandbox">Testes</option><option value="production">Produção</option></select><input className="field" name="accessToken" type="password" required autoComplete="off" placeholder="Access Token" /><input className="field sm:col-span-2" name="webhookSecret" type="password" required autoComplete="off" placeholder="Assinatura secreta do Webhook" /><p className="text-xs text-muted sm:col-span-2">Cadastre na aplicação Mercado Pago a URL: {`${process.env.NEXT_PUBLIC_APP_URL ?? "https://seu-dominio"}/api/webhooks/mercado-pago?organizationId=${organization.id}`}</p><button className="primary-button sm:w-fit">Conectar e validar</button></ActionForm>{mercadoPago && <ActionForm action={testMercadoPagoIntegration} successMessage="Conexão Mercado Pago validada." className="mt-3"><button className="secondary-button"><RefreshCcw className="mr-2 size-4" />Testar conexão atual</button></ActionForm>}</div></div>,
        },
      ]}
    />

    {(integration || mercadoPago) && hasOrganizationPermission(organization.role, "integrations.manage") && <details className="mb-5 rounded-2xl border border-red-100 bg-white p-4"><summary className="cursor-pointer text-xs font-bold text-red-700">Opções avançadas das conexões</summary><div className="mt-3 flex flex-wrap gap-2">{integration && <ActionForm action={disconnectAsaasAccount} successMessage="Conta Asaas desconectada."><button className="secondary-button text-red-700">Desconectar Asaas</button></ActionForm>}{mercadoPago && <ActionForm action={disconnectMercadoPagoAccount} successMessage="Conta Mercado Pago desconectada."><button className="secondary-button text-red-700">Desconectar Mercado Pago</button></ActionForm>}</div></details>}
    {canManage && <details className="panel mb-5" open={!allCharges.length}><summary className="cursor-pointer text-lg font-extrabold text-brand">Emitir novo pagamento</summary><div className="mt-5"><ChargeCreateForm providers={[...(integration?.status === "active" ? ["asaas" as const] : []), ...(mercadoPago?.status === "active" ? ["mercado_pago" as const] : [])]} entries={pendingEntries.filter((entry) => !activeEntryIds.has(entry.id)).map((entry) => ({ id: entry.id, description: entry.description, amount: money(entry.amountInCents), dueDate: date(entry.dueDate), clientName: entry.clientName ?? "", clientEmail: entry.clientEmail ?? "", clientPhone: entry.clientPhone ?? "" }))} /></div></details>}

    <details className="panel mb-5"><summary className="cursor-pointer text-lg font-extrabold text-brand">Homologação e prontidão operacional</summary><p className="mt-2 text-sm text-muted">O painel reconhece evidências reais registradas pelo Asaas. Execute o roteiro primeiro em Testes e repita em Produção com valores controlados.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[
      ["Conta autenticada", Boolean(metadata.testedAt)],
      ["Webhook ativo", webhookStatus === "active"],
      ["Emissão validada", events.some((event) => event.eventType === "charge_created")],
      ["Pagamento e baixa", events.some((event) => ["PAYMENT_RECEIVED", "PAYMENT_CONFIRMED"].includes(event.eventType))],
      ["Cancelamento/estorno", events.some((event) => ["PAYMENT_DELETED", "PAYMENT_REFUNDED", "PAYMENT_PARTIALLY_REFUNDED"].includes(event.eventType))],
    ].map(([label, ready]) => <div className={`rounded-xl border p-3 text-sm font-bold ${ready ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-amber-200 bg-amber-50 text-amber-800"}`} key={String(label)}>{ready ? "✓" : "○"} {String(label)}</div>)}</div><ol className="mt-4 list-decimal space-y-1 pl-5 text-sm text-muted"><li>Emitir Pix, boleto, link e cartão e conferir valores, vencimento e pagador.</li><li>Pagar uma cobrança e confirmar a baixa automática da conta a receber.</li><li>Vencer outra cobrança e validar a régua e o status de inadimplência.</li><li>Cancelar uma pendente e estornar uma paga, conferindo a reabertura financeira.</li><li>Repetir em produção e registrar as evidências acima antes da liberação geral.</li></ol></details>

    <form className="panel mb-5 grid gap-3 md:grid-cols-3 xl:grid-cols-6"><label className="grid gap-1 text-xs font-bold xl:col-span-2">Buscar<input className="field" name="busca" defaultValue={query.busca} placeholder="Paciente, descrição ou CPF/CNPJ" /></label><label className="grid gap-1 text-xs font-bold">Situação<select className="field" name="status" defaultValue={query.status ?? "all"}><option value="all">Todas</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-1 text-xs font-bold">Meio<select className="field" name="meio" defaultValue={query.meio ?? "all"}><option value="all">Todos</option><option value="pix">Pix</option><option value="boleto">Boleto</option><option value="link">Link</option><option value="credit_card">Cartão</option></select></label><label className="grid gap-1 text-xs font-bold">Vence de<input className="field" type="date" name="inicio" defaultValue={query.inicio} /></label><label className="grid gap-1 text-xs font-bold">Até<input className="field" type="date" name="fim" defaultValue={query.fim} /></label><button className="primary-button md:w-fit">Filtrar</button><Link className="secondary-button md:w-fit" href="/financeiro/cobrancas">Limpar</Link></form>

    <section className="grid gap-4">{charges.map((charge) => { const chargeEvents = events.filter((event) => event.chargeId === charge.id); const paymentUrl = charge.invoiceUrl || charge.bankSlipUrl; return <article className="panel" key={charge.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-extrabold">{charge.description}</h2><span className="status-pill">{statusLabels[charge.status] ?? charge.status}</span>{charge.chargeMode !== "single" && <span className="status-pill">{charge.chargeMode === "recurring" ? "Mensal" : `${charge.installmentCount} parcelas`}</span>}</div><p className="mt-1 text-sm text-muted">{charge.customerName} · {charge.customerDocument || "Documento não armazenado"} · vence {date(charge.dueDate)}</p><p className="text-xs text-muted">{charge.customerEmail || "Sem e-mail"} · {charge.customerPhone || "Sem telefone"}</p></div><p className="text-2xl font-extrabold">{money(charge.amountInCents)}</p></div>
        <div className="mt-4 flex flex-wrap gap-2">{paymentUrl && <><a className="primary-button" href={paymentUrl} target="_blank" rel="noreferrer">Abrir pagamento</a><CopyButton value={paymentUrl} label="Copiar link" /></>}{charge.pixQrCodePayload && <CopyButton value={charge.pixQrCodePayload} label="Copiar Pix" />}{charge.bankSlipIdentificationField && <CopyButton value={charge.bankSlipIdentificationField} label="Copiar linha digitável" />}{canManage && paymentUrl && charge.customerPhone && <ActionForm action={sendPaymentChargeWhatsApp} successMessage="Cobrança enfileirada no WhatsApp."><input type="hidden" name="id" value={charge.id} /><button className="secondary-button">Enviar por WhatsApp</button></ActionForm>}</div>
        {charge.pixQrCodeImage && <details className="mt-4"><summary className="cursor-pointer text-sm font-bold text-brand">Exibir QR Code Pix</summary><Image className="mt-3 rounded-xl border" alt="QR Code Pix" width={180} height={180} unoptimized src={`data:image/png;base64,${charge.pixQrCodeImage}`} /></details>}
        {canManage && ["pending", "overdue"].includes(charge.status) && <details className="mt-4 rounded-2xl border p-4"><summary className="cursor-pointer text-sm font-extrabold">Alterar ou cancelar</summary><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_auto]"><ActionForm action={updatePaymentCharge} successMessage="Cobrança atualizada." className="grid gap-2 sm:grid-cols-3"><input type="hidden" name="id" value={charge.id} /><input className="field" name="description" defaultValue={charge.description} required /><input className="field" name="amount" defaultValue={(charge.amountInCents / 100).toFixed(2).replace(".", ",")} required /><input className="field" name="dueDate" type="date" defaultValue={charge.dueDate} required /><button className="secondary-button sm:w-fit">Salvar alterações</button></ActionForm><ActionForm action={cancelPaymentCharge} successMessage="Cobrança cancelada."><input type="hidden" name="id" value={charge.id} /><button className="secondary-button text-red-700">Cancelar cobrança</button></ActionForm></div></details>}
        {canManage && charge.status === "paid" && <div className="mt-4"><ActionForm action={refundPaymentCharge} successMessage="Estorno solicitado ao Asaas."><input type="hidden" name="id" value={charge.id} /><button className="secondary-button text-red-700">Solicitar estorno</button></ActionForm></div>}
        <details className="mt-4"><summary className="cursor-pointer text-sm font-bold text-brand">Histórico ({chargeEvents.length})</summary><ol className="mt-3 grid gap-2 border-l pl-4">{chargeEvents.map((event) => <li key={event.id}><p className="text-sm font-bold">{eventLabels[event.eventType] ?? event.eventType}</p><p className="text-xs text-muted">{event.createdAt.toLocaleString("pt-BR")} · {statusLabels[event.status] ?? event.status}</p></li>)}</ol></details>
      </article>; })}{!charges.length && <p className="empty-state">Nenhuma cobrança encontrada para os filtros.</p>}</section>
    {pages > 1 && <nav className="mt-5 flex items-center justify-between"><Link className={`secondary-button ${currentPage === 1 ? "pointer-events-none opacity-50" : ""}`} href={`?${params.toString()}&pagina=${currentPage - 1}`}>Anterior</Link><p className="text-sm font-bold">Página {currentPage} de {pages}</p><Link className={`secondary-button ${currentPage === pages ? "pointer-events-none opacity-50" : ""}`} href={`?${params.toString()}&pagina=${currentPage + 1}`}>Próxima</Link></nav>}
  </div>;
}
