import { eq } from "drizzle-orm";
import { db } from "@/db";
import { crmOpportunities, crmStages } from "@/db/schema";

const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value / 100);
export async function CrmReportsPanel({ organizationId }: { organizationId: string }) {
  const opportunities = await db.select({ status: crmOpportunities.status, value: crmOpportunities.valueInCents, source: crmOpportunities.source, stage: crmStages.name }).from(crmOpportunities).innerJoin(crmStages, eq(crmStages.id, crmOpportunities.stageId)).where(eq(crmOpportunities.organizationId, organizationId));
  const won = opportunities.filter((item) => item.status === "won"); const lost = opportunities.filter((item) => item.status === "lost"); const closed = won.length + lost.length; const revenue = won.reduce((sum, item) => sum + (item.value ?? 0), 0);
  const sources = [...new Set(opportunities.map((item) => item.source))].map((source) => ({ source, total: opportunities.filter((item) => item.source === source).length, won: opportunities.filter((item) => item.source === source && item.status === "won").length }));
  return <section className="mt-5 min-w-0"><div className="mb-5"><h2 className="text-lg font-extrabold">Relatórios do CRM</h2><p className="mt-1 text-sm text-muted">Conversão, receita e origem das oportunidades.</p></div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article className="panel"><p className="text-3xl font-extrabold">{opportunities.length}</p><p className="text-sm text-muted">oportunidades</p></article><article className="panel"><p className="text-3xl font-extrabold">{closed ? Math.round(won.length / closed * 100) : 0}%</p><p className="text-sm text-muted">conversão entre encerradas</p></article><article className="panel"><p className="text-3xl font-extrabold">{money(revenue)}</p><p className="text-sm text-muted">receita ganha</p></article><article className="panel"><p className="text-3xl font-extrabold">{lost.length}</p><p className="text-sm text-muted">oportunidades perdidas</p></article></section><section className="panel mt-5"><h2 className="text-xl font-extrabold">Desempenho por origem</h2><div className="mt-4 divide-y">{sources.map((item) => <div className="grid grid-cols-3 gap-3 py-3 text-sm" key={item.source}><strong>{item.source}</strong><span>{item.total} oportunidades</span><span>{item.won} ganhas</span></div>)}</div></section></section>;
}
