import Link from "next/link";
import { updateProcedureReturnContact } from "@/actions/procedure-returns";
import { getProcedureReturns } from "@/lib/procedure-returns";
import { formatOrganizationDateTime } from "@/lib/appointment-safety";
import { ActionForm } from "./action-form";

export const returnStateLabels: Record<string, string> = { overdue: "Vencido", upcoming: "Próximo", future: "Futuro", scheduled: "Já agendado", contacted: "Contato registrado", dismissed: "Dispensado" };

export async function ProcedureReturnsPanel({ organizationId, timezone, canManage, filter = "due", search = "" }: { organizationId: string; timezone: string; canManage: boolean; filter?: string; search?: string }) {
  const rows = await getProcedureReturns(organizationId, timezone);
  const term = search.trim().toLocaleLowerCase("pt-BR");
  const filtered = rows.filter((item) => (filter === "all" || (filter === "due" ? ["overdue", "upcoming"].includes(item.state) : item.state === filter)) && (!term || `${item.client} ${item.service}`.toLocaleLowerCase("pt-BR").includes(term)));
  return <section className="panel mt-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-extrabold">Retornos por procedimento</h2><p className="mt-2 text-sm text-muted">Prazos definidos nos atendimentos concluídos. Um novo agendamento suspende o convite.</p></div><Link href="/servicos" className="secondary-button">Configurar procedimentos</Link></div>
    <div className="mt-4 flex flex-wrap gap-2">{["overdue", "upcoming", "scheduled", "contacted"].map((state) => <span key={state} className="status-pill">{returnStateLabels[state]}: {rows.filter((item) => item.state === state).length}</span>)}</div>
    <form className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="tab" value="retornos" /><input name="returnSearch" className="field" defaultValue={search} placeholder="Buscar cliente ou procedimento" aria-label="Buscar retornos" /><select name="returnState" className="field" defaultValue={filter} aria-label="Situação do retorno"><option value="due">Próximos e vencidos</option><option value="all">Todos</option>{Object.entries(returnStateLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><button className="secondary-button">Filtrar</button></form>
    <div className="mt-5 divide-y">{filtered.map((item) => <article className="grid gap-4 py-5 lg:grid-cols-[1fr_1fr]" key={item.id}><div><div className="flex flex-wrap gap-3"><Link href={`/clientes/${item.clientId}`} className="font-extrabold text-brand">{item.client}</Link><span className="status-pill">{returnStateLabels[item.state]}</span></div><p className="mt-2 font-bold">{item.service}</p><p className="mt-1 text-sm text-muted">Última realização: {formatOrganizationDateTime(item.performedAt, timezone)}<br />Retorno sugerido: {item.dueDate.split("-").reverse().join("/")}</p>{item.nextAppointment && <p className="mt-2 text-sm font-bold text-brand">Agendado para {formatOrganizationDateTime(item.nextAppointment, timezone)}</p>}{item.contactedAt && <p className="mt-2 text-xs text-muted">Contato registrado em {formatOrganizationDateTime(item.contactedAt, timezone)}</p>}<Link className="mt-2 inline-block text-sm font-bold text-brand" href={`/atendimento/${item.appointmentId}`}>Ver atendimento e ajustar retorno</Link>{!canManage && item.contactNote && <p className="mt-2 text-sm text-muted">{item.contactNote}</p>}</div>
      {canManage && <ActionForm action={updateProcedureReturnContact} successMessage="Acompanhamento atualizado." className="grid gap-2"><input type="hidden" name="id" value={item.id} /><label className="grid gap-2 text-sm font-bold">Situação do contato<select className="field" name="contactStatus" defaultValue={item.contactStatus}><option value="pending">A contatar</option><option value="contacted" disabled={Boolean(item.nextAppointment)}>Contato realizado</option><option value="dismissed">Dispensar convite</option></select></label><textarea className="field min-h-20" name="contactNote" maxLength={2000} defaultValue={item.contactNote ?? ""} aria-label={`Observação do retorno de ${item.client}`} placeholder="Observação do contato" /><button className="secondary-button w-fit">Salvar acompanhamento</button></ActionForm>}
    </article>)}{!filtered.length && <p className="empty-state">Nenhum retorno nesta seleção. Configure os prazos dos procedimentos e confirme-os ao concluir os atendimentos.</p>}</div>
  </section>;
}
