import { and, asc, eq, gte, lt } from "drizzle-orm";
import Link from "next/link";

import { upsertFinancialBudget } from "@/actions/app";
import { ActionForm } from "@/components/action-form";
import { PageHeader } from "@/components/page-header";
import { db } from "@/db";
import { clients, financialBudgets, financialCategories, financialCostCenters, financialEntries } from "@/db/schema";
import { organizationDate } from "@/lib/appointment-safety";
import { hasOrganizationPermission } from "@/lib/permissions";
import { requireOrganization } from "@/lib/session";

const money = (value: number) => (value / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
function monthRange(month: string) { const [year, number] = month.split("-").map(Number); const next = new Date(Date.UTC(year, number, 1)); return [`${month}-01`, `${next.getUTCFullYear()}-${String(next.getUTCMonth() + 1).padStart(2, "0")}-01`] as const; }
function previousMonth(month: string) { const [year, number] = month.split("-").map(Number); const value = new Date(Date.UTC(year, number - 2, 1)); return `${value.getUTCFullYear()}-${String(value.getUTCMonth() + 1).padStart(2, "0")}`; }

export default async function FinancialReportsPage({ searchParams }: { searchParams: Promise<{ mes?: string }> }) {
  const { organization } = await requireOrganization(); const query = await searchParams; const current = organizationDate(new Date(), organization.timezone).slice(0, 7); const month = /^\d{4}-\d{2}$/.test(query.mes ?? "") ? query.mes! : current; const previous = previousMonth(month); const [start, end] = monthRange(month); const [previousStart, previousEnd] = monthRange(previous); const today = organizationDate(new Date(), organization.timezone); const canManage = hasOrganizationPermission(organization.role, "finance.manage");
  const [entries, previousEntries, categories, centers, budgets, delinquent] = await Promise.all([
    db.select().from(financialEntries).where(and(eq(financialEntries.organizationId, organization.id), gte(financialEntries.dueDate, start), lt(financialEntries.dueDate, end))),
    db.select().from(financialEntries).where(and(eq(financialEntries.organizationId, organization.id), gte(financialEntries.dueDate, previousStart), lt(financialEntries.dueDate, previousEnd))),
    db.select().from(financialCategories).where(eq(financialCategories.organizationId, organization.id)).orderBy(asc(financialCategories.name)),
    db.select().from(financialCostCenters).where(eq(financialCostCenters.organizationId, organization.id)).orderBy(asc(financialCostCenters.name)),
    db.select().from(financialBudgets).where(and(eq(financialBudgets.organizationId, organization.id), eq(financialBudgets.month, month))),
    db.select({ clientId: clients.id, clientName: clients.name, amount: financialEntries.amountInCents, dueDate: financialEntries.dueDate }).from(financialEntries).innerJoin(clients, eq(clients.id, financialEntries.clientId)).where(and(eq(financialEntries.organizationId, organization.id), eq(financialEntries.type, "receivable"), eq(financialEntries.status, "pending"), lt(financialEntries.dueDate, today))).orderBy(asc(financialEntries.dueDate)),
  ]);
  const result = (items: typeof entries) => ({ revenue: items.filter((item) => item.type === "receivable" && item.status === "received").reduce((sum, item) => sum + item.amountInCents, 0), expenses: items.filter((item) => item.type === "payable" && item.status === "paid").reduce((sum, item) => sum + item.amountInCents, 0) }); const actual = result(entries); const prior = result(previousEntries); const net = actual.revenue - actual.expenses; const margin = actual.revenue ? Math.round(net / actual.revenue * 100) : 0;
  const categoryRows = categories.map((category) => { const categoryEntries = entries.filter((item) => item.categoryId === category.id && ((category.type === "payable" && item.status === "paid") || (category.type === "receivable" && item.status === "received"))); const realized = categoryEntries.reduce((sum, item) => sum + item.amountInCents, 0); const budget = budgets.filter((item) => item.categoryId === category.id).reduce((sum, item) => sum + item.amountInCents, 0); return { ...category, realized, budget, variance: category.type === "payable" ? budget - realized : realized - budget }; }).filter((row) => row.realized || row.budget);
  const delinquency = delinquent.reduce((map, item) => { const currentItem = map.get(item.clientId) ?? { id: item.clientId, name: item.clientName, amount: 0, oldest: item.dueDate, count: 0 }; currentItem.amount += item.amount; currentItem.count += 1; if (item.dueDate < currentItem.oldest) currentItem.oldest = item.dueDate; map.set(item.clientId, currentItem); return map; }, new Map<string, { id: string; name: string; amount: number; oldest: string; count: number }>()); const delinquentClients = [...delinquency.values()].sort((a, b) => b.amount - a.amount);
  const maxChart = Math.max(actual.revenue, actual.expenses, prior.revenue, prior.expenses, 1); const bars = [{ label: `Receitas ${previous}`, value: prior.revenue, color: "bg-emerald-300" }, { label: `Receitas ${month}`, value: actual.revenue, color: "bg-emerald-700" }, { label: `Despesas ${previous}`, value: prior.expenses, color: "bg-red-300" }, { label: `Despesas ${month}`, value: actual.expenses, color: "bg-red-700" }];
  return <div className="page-wrap"><Link className="mb-4 inline-flex text-sm font-bold text-brand" href={`/financeiro?mes=${month}`}>← Voltar ao fluxo de caixa</Link><PageHeader eyebrow="Financeiro gerencial" title="DRE e indicadores" description="Análises calculadas localmente com os lançamentos do Aggenda, sem serviços externos pagos." />
    <form className="panel mb-5 flex flex-wrap items-end gap-3"><label className="grid gap-1 text-xs font-bold">Competência<input className="field" type="month" name="mes" defaultValue={month} /></label><button className="primary-button">Visualizar</button></form>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article className="panel"><p className="text-sm text-muted">Receita realizada</p><p className="mt-2 text-2xl font-extrabold text-emerald-700">{money(actual.revenue)}</p></article><article className="panel"><p className="text-sm text-muted">Despesas realizadas</p><p className="mt-2 text-2xl font-extrabold text-red-700">{money(actual.expenses)}</p></article><article className="panel"><p className="text-sm text-muted">Resultado</p><p className="mt-2 text-2xl font-extrabold">{money(net)}</p></article><article className="panel"><p className="text-sm text-muted">Margem operacional</p><p className="mt-2 text-2xl font-extrabold">{margin}%</p></article></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-2"><article className="panel"><h2 className="text-lg font-extrabold">Comparação mensal</h2><div className="mt-5 grid h-64 grid-cols-4 items-end gap-4 border-b px-3">{bars.map((bar) => <div className="flex h-full flex-col justify-end text-center" key={bar.label}><p className="mb-2 text-xs font-bold">{money(bar.value)}</p><div className={`${bar.color} mx-auto w-full max-w-16 rounded-t-lg`} style={{ height: `${Math.max(3, bar.value / maxChart * 75)}%` }} /><p className="mt-2 min-h-10 text-[10px] text-muted">{bar.label}</p></div>)}</div></article><article className="panel"><h2 className="text-lg font-extrabold">DRE simplificada</h2><div className="mt-4 divide-y"><div className="flex justify-between py-3"><span>Receita operacional</span><strong className="text-emerald-700">{money(actual.revenue)}</strong></div><div className="flex justify-between py-3"><span>(−) Despesas operacionais</span><strong className="text-red-700">{money(actual.expenses)}</strong></div><div className="flex justify-between py-3 text-lg"><strong>Resultado operacional</strong><strong>{money(net)}</strong></div></div><p className="mt-4 text-xs text-muted">Relatório gerencial simplificado. Não substitui a escrituração contábil oficial.</p></article></section>
    <section className="panel mt-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-extrabold">Orçado × realizado</h2><p className="text-sm text-muted">Variação positiva indica desempenho favorável à categoria.</p></div></div>{canManage && <ActionForm action={upsertFinancialBudget} successMessage="Orçamento atualizado." className="mt-4 grid gap-3 md:grid-cols-5"><input type="hidden" name="month" value={month} /><select className="field" name="categoryId" required><option value="">Categoria</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="field" name="costCenterId"><option value="">Todos os centros</option>{centers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input className="field" name="amount" inputMode="decimal" required placeholder="Valor orçado" /><button className="primary-button">Salvar orçamento</button></ActionForm>}<div className="mt-4 divide-y">{categoryRows.map((row) => <div className="grid gap-2 py-3 text-sm md:grid-cols-4" key={row.id}><strong>{row.name}</strong><span>Orçado {money(row.budget)}</span><span>Realizado {money(row.realized)}</span><strong className={row.variance >= 0 ? "text-emerald-700" : "text-red-700"}>Variação {money(row.variance)}</strong></div>)}{!categoryRows.length && <p className="empty-state">Cadastre categorias, orçamento ou lançamentos realizados.</p>}</div></section>
    <section className="panel mt-5"><h2 className="text-lg font-extrabold">Inadimplência por cliente</h2><p className="text-sm text-muted">Somente contas a receber vencidas e vinculadas a clientes.</p><div className="mt-4 divide-y">{delinquentClients.map((item) => <div className="grid gap-2 py-3 text-sm md:grid-cols-[1fr_auto_auto]" key={item.id}><Link className="font-bold" href={`/clientes/${item.id}`}>{item.name}</Link><span>{item.count} pendência(s) · desde {new Date(`${item.oldest}T12:00:00Z`).toLocaleDateString("pt-BR")}</span><strong className="text-red-700">{money(item.amount)}</strong></div>)}{!delinquentClients.length && <p className="empty-state">Nenhum cliente com recebimento vencido.</p>}</div></section>
  </div>;
}
