import { and, asc, desc, eq } from "drizzle-orm";
import { AlertTriangle, Boxes, Trash2 } from "lucide-react";
import { createInventoryProduct, moveInventory, removeServiceInventoryItem, setServiceInventoryItem } from "@/actions/inventory";
import { ActionForm } from "@/components/action-form";
import { PageHeader } from "@/components/page-header";
import { db } from "@/db";
import { inventoryMovements, inventoryProducts, serviceInventoryItems, services } from "@/db/schema";
import { hasOrganizationPermission } from "@/lib/permissions";
import { requireOrganization } from "@/lib/session";
const units: Record<string, string> = { unit: "un", ml: "ml", g: "g", kg: "kg", l: "l", dose: "dose" };
const qty = (value: number) => (value / 1000).toLocaleString("pt-BR", { maximumFractionDigits: 3 });
export const metadata = { title: "Estoque" };
export default async function InventoryPage() { const { organization } = await requireOrganization(); const canManage = hasOrganizationPermission(organization.role, "inventory.manage"); const [products, serviceList, recipe, movements] = await Promise.all([db.select().from(inventoryProducts).where(eq(inventoryProducts.organizationId, organization.id)).orderBy(asc(inventoryProducts.name)), db.select({ id: services.id, name: services.name }).from(services).where(and(eq(services.organizationId, organization.id), eq(services.isActive, true))).orderBy(asc(services.name)), db.select({ serviceId: serviceInventoryItems.serviceId, serviceName: services.name, productId: serviceInventoryItems.productId, productName: inventoryProducts.name, unit: inventoryProducts.unit, quantity: serviceInventoryItems.quantityMillis }).from(serviceInventoryItems).innerJoin(services, eq(services.id, serviceInventoryItems.serviceId)).innerJoin(inventoryProducts, eq(inventoryProducts.id, serviceInventoryItems.productId)).where(eq(serviceInventoryItems.organizationId, organization.id)).orderBy(asc(services.name)), db.select({ id: inventoryMovements.id, productName: inventoryProducts.name, unit: inventoryProducts.unit, type: inventoryMovements.type, quantity: inventoryMovements.quantityMillis, balance: inventoryMovements.balanceAfterMillis, notes: inventoryMovements.notes, createdAt: inventoryMovements.createdAt }).from(inventoryMovements).innerJoin(inventoryProducts, eq(inventoryProducts.id, inventoryMovements.productId)).where(eq(inventoryMovements.organizationId, organization.id)).orderBy(desc(inventoryMovements.createdAt)).limit(30)]); const low = products.filter((item) => item.currentQuantityMillis <= item.minimumQuantityMillis);
return <div className="page-wrap"><PageHeader eyebrow="Operação" title="Controle de estoque" description="Cadastre insumos e defina quanto cada procedimento consome ao ser concluído." /><section className="grid gap-4 sm:grid-cols-3"><article className="panel"><Boxes className="size-5 text-brand" /><p className="mt-4 text-3xl font-extrabold">{products.length}</p><p className="text-sm text-muted">produtos cadastrados</p></article><article className="panel"><AlertTriangle className="size-5 text-amber-600" /><p className="mt-4 text-3xl font-extrabold">{low.length}</p><p className="text-sm text-muted">no mínimo ou abaixo</p></article><article className="panel"><p className="text-sm text-muted">Valor estimado em estoque</p><p className="mt-4 text-2xl font-extrabold">{(products.reduce((sum, item) => sum + (item.costInCents ?? 0) * item.currentQuantityMillis / 1000, 0) / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</p></article></section>
{canManage && <section className="mt-5 grid gap-5 xl:grid-cols-2"><ActionForm action={createInventoryProduct} successMessage="Produto cadastrado." className="panel form-stack"><h2 className="text-lg font-extrabold">Novo produto</h2><div className="grid gap-3 sm:grid-cols-2"><input className="field" name="name" required placeholder="Nome do produto" /><input className="field" name="sku" placeholder="Código/SKU opcional" /><select className="field" name="unit"><option value="unit">Unidade</option><option value="ml">Mililitro</option><option value="g">Grama</option><option value="kg">Quilograma</option><option value="l">Litro</option><option value="dose">Dose</option></select><input className="field" name="cost" inputMode="decimal" placeholder="Custo por unidade" /><input className="field" name="initialQuantity" inputMode="decimal" required placeholder="Quantidade inicial" /><input className="field" name="minimumQuantity" inputMode="decimal" required placeholder="Estoque mínimo" /></div><button className="primary-button">Cadastrar produto</button></ActionForm><ActionForm action={setServiceInventoryItem} successMessage="Produto vinculado ao procedimento." className="panel form-stack"><h2 className="text-lg font-extrabold">Consumo por procedimento</h2><select className="field" name="serviceId" required><option value="">Procedimento</option>{serviceList.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="field" name="productId" required><option value="">Produto utilizado</option>{products.map((item) => <option key={item.id} value={item.id}>{item.name} ({units[item.unit] ?? item.unit})</option>)}</select><input className="field" name="quantity" inputMode="decimal" required placeholder="Quantidade consumida" /><button className="primary-button">Adicionar à ficha técnica</button></ActionForm></section>}
<section className="panel mt-5"><h2 className="text-lg font-extrabold">Posição do estoque</h2><div className="mt-4 divide-y">{products.map((item) => <article className="grid gap-3 py-4 lg:grid-cols-[1fr_auto_1fr] lg:items-center" key={item.id}><div><div className="flex flex-wrap gap-2"><p className="font-extrabold">{item.name}</p>{item.currentQuantityMillis <= item.minimumQuantityMillis && <span className="rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-800">Reposição necessária</span>}</div><p className="text-xs text-muted">{item.sku || "Sem SKU"} · mínimo {qty(item.minimumQuantityMillis)} {units[item.unit] ?? item.unit}</p></div><strong className="text-xl text-brand">{qty(item.currentQuantityMillis)} {units[item.unit] ?? item.unit}</strong>{canManage && <ActionForm action={moveInventory} successMessage="Estoque movimentado." className="flex flex-wrap gap-2"><input type="hidden" name="productId" value={item.id} /><select className="field max-w-40" name="type"><option value="entry">Entrada</option><option value="adjustment_add">Ajuste positivo</option><option value="adjustment_remove">Ajuste negativo</option><option value="loss">Perda</option></select><input className="field max-w-32" name="quantity" inputMode="decimal" required placeholder="Quantidade" /><input className="field max-w-44" name="notes" placeholder="Observação" /><button className="secondary-button">Movimentar</button></ActionForm>}</article>)}</div></section>
<section className="mt-5 grid gap-5 xl:grid-cols-2"><article className="panel"><h2 className="text-lg font-extrabold">Fichas técnicas</h2><div className="mt-4 divide-y">{recipe.map((item) => <div className="flex items-center justify-between gap-3 py-3 text-sm" key={`${item.serviceId}-${item.productId}`}><span><strong>{item.serviceName}</strong><br />{item.productName}: {qty(item.quantity)} {units[item.unit] ?? item.unit}</span>{canManage && <ActionForm action={removeServiceInventoryItem} successMessage="Item removido."><input type="hidden" name="serviceId" value={item.serviceId} /><input type="hidden" name="productId" value={item.productId} /><button className="icon-button" aria-label="Remover item"><Trash2 className="size-4" /></button></ActionForm>}</div>)}</div></article><article className="panel"><h2 className="text-lg font-extrabold">Movimentações recentes</h2><div className="mt-4 divide-y">{movements.map((item) => <div className="grid grid-cols-[1fr_auto] gap-2 py-3 text-sm" key={item.id}><span><strong>{item.productName}</strong><br /><span className="text-xs text-muted">{item.type} · {item.createdAt.toLocaleString("pt-BR")}</span></span><span className={item.quantity >= 0 ? "text-emerald-700" : "text-red-700"}>{item.quantity >= 0 ? "+" : ""}{qty(item.quantity)} {units[item.unit] ?? item.unit}<br /><span className="text-xs text-muted">saldo {qty(item.balance)}</span></span></div>)}</div></article></section></div>; }
