"use client";

import { Search } from "lucide-react";
import { useDeferredValue, useMemo, useState } from "react";

export type StockProductRow = { id: string; name: string; presentation: string; brand: string; quantity: number; quantityLabel: string; costUnit: string; costTotal: string; saleUnit: string; saleTotal: string; minimum: number; categoryId: string | null; category: string; subcategoryId: string | null; subcategory: string; hasConsumption: boolean };
const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();

export function StockProductList({ products, categories, subcategories }: { products: StockProductRow[]; categories: Array<{ id: string; name: string }>; subcategories: Array<{ id: string; categoryId: string; name: string }> }) {
  const [query, setQuery] = useState(""); const deferredQuery = useDeferredValue(query);
  const [status, setStatus] = useState("all"); const [categoryId, setCategoryId] = useState(""); const [subcategoryId, setSubcategoryId] = useState("");
  const filteredSubcategories = subcategories.filter((item) => item.categoryId === categoryId);
  const filtered = useMemo(() => products.filter((item) => {
    const matchesQuery = normalize(`${item.name} ${item.presentation} ${item.brand}`).includes(normalize(deferredQuery));
    const matchesStatus = status === "all" || (status === "stock" && item.quantity > 0) || (status === "consumption" && item.hasConsumption) || (status === "low" && item.quantity <= item.minimum);
    return matchesQuery && matchesStatus && (!categoryId || item.categoryId === categoryId) && (!subcategoryId || item.subcategoryId === subcategoryId);
  }), [products, deferredQuery, status, categoryId, subcategoryId]);
  return <section className="panel mt-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-extrabold">Produtos</h2><p className="text-sm text-muted">Consulte saldos, custos e valores de venda.</p></div><label className="relative w-full sm:max-w-sm"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted" /><input className="field w-full pl-9" type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar produto, apresentação ou marca" /></label></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><select className="field" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">Todos os produtos</option><option value="stock">Produtos em estoque</option><option value="consumption">Produtos para consumo</option><option value="low">Abaixo do estoque mínimo</option></select><select className="field" value={categoryId} onChange={(event) => { setCategoryId(event.target.value); setSubcategoryId(""); }}><option value="">Todas as categorias</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="field" value={subcategoryId} onChange={(event) => setSubcategoryId(event.target.value)} disabled={!categoryId}><option value="">Todas as subcategorias</option>{filteredSubcategories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="border-b text-xs uppercase text-muted"><tr><th className="p-3">Produto</th><th className="p-3">Apresentação</th><th className="p-3">Marca</th><th className="p-3 text-right">Qtd.</th><th className="p-3 text-right">Custo unit.</th><th className="p-3 text-right">Custo total</th><th className="p-3 text-right">Venda unit.</th><th className="p-3 text-right">Venda total</th></tr></thead><tbody className="divide-y">{filtered.map((item) => <tr key={item.id}><td className="p-3"><strong>{item.name}</strong><p className="text-xs text-muted">{[item.category, item.subcategory].filter(Boolean).join(" · ") || "Sem categoria"}</p></td><td className="p-3">{item.presentation}</td><td className="p-3">{item.brand}</td><td className={`p-3 text-right font-bold ${item.quantity <= item.minimum ? "text-red-700" : ""}`}>{item.quantityLabel}</td><td className="p-3 text-right">{item.costUnit}</td><td className="p-3 text-right">{item.costTotal}</td><td className="p-3 text-right">{item.saleUnit}</td><td className="p-3 text-right font-bold text-brand">{item.saleTotal}</td></tr>)}</tbody></table>{!filtered.length && <p className="py-8 text-center text-sm text-muted">Nenhum produto encontrado para os filtros selecionados.</p>}</div></section>;
}
