import { and, asc, count, desc, eq, gte, isNull } from "drizzle-orm";
import Link from "next/link";
import { closeCash, createCommissionRule, diagnoseNfseCompatibility, generateCommissions, importOfx, markCommissionPaid, openCash, reconcileOfx, registerFiscalDocument, requestNfseActivation, saveNfseFiscalProfile } from "@/actions/financial-operations";
import { connectAsaasAccount } from "@/actions/payment-charges";
import { ActionForm } from "@/components/action-form";
import { PageHeader } from "@/components/page-header";
import { db } from "@/db";
import { bankImportTransactions, cashClosings, commissionEntries, commissionRules, financialAccounts, financialEntries, fiscalDocuments, organizationFinancialIntegrations, professionals, services } from "@/db/schema";
import { organizationDate } from "@/lib/appointment-safety";
import { readNfseProfile } from "@/lib/nfse-routing";
import { getOrganizationServicePlan, nfsePublicOffer } from "@/lib/service-plans";
import { requireOrganization } from "@/lib/session";

const money = (value: number) => (value / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
export default async function FinancialOperationsPage({ searchParams }: { searchParams: Promise<{ mes?: string }> }) {
  const { organization } = await requireOrganization(); const query = await searchParams; const current = organizationDate(new Date(), organization.timezone).slice(0, 7); const month = /^\d{4}-\d{2}$/.test(query.mes ?? "") ? query.mes! : current;
  const monthStart = new Date(`${month}-01T00:00:00-03:00`);
  const [professionalsList, servicesList, accounts, rules, commissions, openCashList, transactions, pendingEntries, integrations, documents, [nfseUsage], servicePlan] = await Promise.all([
    db.select({ id: professionals.id, name: professionals.name }).from(professionals).where(eq(professionals.organizationId, organization.id)).orderBy(asc(professionals.name)),
    db.select({ id: services.id, name: services.name }).from(services).where(eq(services.organizationId, organization.id)).orderBy(asc(services.name)),
    db.select().from(financialAccounts).where(eq(financialAccounts.organizationId, organization.id)).orderBy(asc(financialAccounts.name)),
    db.select({ id: commissionRules.id, professional: professionals.name, service: services.name, type: commissionRules.calculationType, value: commissionRules.value }).from(commissionRules).innerJoin(professionals, eq(professionals.id, commissionRules.professionalId)).leftJoin(services, eq(services.id, commissionRules.serviceId)).where(eq(commissionRules.organizationId, organization.id)),
    db.select({ id: commissionEntries.id, professional: professionals.name, amount: commissionEntries.amountInCents, base: commissionEntries.baseAmountInCents, status: commissionEntries.status }).from(commissionEntries).innerJoin(professionals, eq(professionals.id, commissionEntries.professionalId)).where(and(eq(commissionEntries.organizationId, organization.id), eq(commissionEntries.competence, month))).orderBy(asc(professionals.name)),
    db.select({ id: cashClosings.id, accountId: cashClosings.accountId, account: financialAccounts.name, opening: cashClosings.openingBalanceInCents, openedAt: cashClosings.openedAt }).from(cashClosings).innerJoin(financialAccounts, eq(financialAccounts.id, cashClosings.accountId)).where(and(eq(cashClosings.organizationId, organization.id), isNull(cashClosings.closedAt))),
    db.select().from(bankImportTransactions).where(and(eq(bankImportTransactions.organizationId, organization.id), eq(bankImportTransactions.status, "unmatched"))).orderBy(desc(bankImportTransactions.occurredOn)).limit(30),
    db.select({ id: financialEntries.id, description: financialEntries.description, amount: financialEntries.amountInCents, type: financialEntries.type, dueDate: financialEntries.dueDate }).from(financialEntries).where(and(eq(financialEntries.organizationId, organization.id), eq(financialEntries.status, "pending"))).orderBy(desc(financialEntries.dueDate)).limit(100),
    db.select({ provider: organizationFinancialIntegrations.provider, environment: organizationFinancialIntegrations.environment, status: organizationFinancialIntegrations.status, metadata: organizationFinancialIntegrations.metadata }).from(organizationFinancialIntegrations).where(eq(organizationFinancialIntegrations.organizationId, organization.id)),
    db.select().from(fiscalDocuments).where(eq(fiscalDocuments.organizationId, organization.id)).orderBy(desc(fiscalDocuments.createdAt)).limit(20),
    db.select({ value: count() }).from(fiscalDocuments).where(and(eq(fiscalDocuments.organizationId, organization.id), gte(fiscalDocuments.createdAt, monthStart))),
    getOrganizationServicePlan(organization.id),
  ]);
  const commissionTotal = commissions.reduce((sum, item) => sum + item.amount, 0);
  const nfseIntegration = integrations.find((item) => item.provider === "nfse");
  const nfseProfile = readNfseProfile(nfseIntegration?.metadata);
  const nfseRequested = nfseIntegration?.status === "requested";
  const nfseReady = nfseIntegration?.status === "active" && Boolean(nfseProfile);
  const needsFiscalProfile = nfseRequested || (Boolean(nfseIntegration) && !nfseProfile);
  const nfseMonthlyLimit = servicePlan.nfseMonthlyLimit || nfsePublicOffer.monthlyLimit;
  const nfseMonthlyPrice = servicePlan.nfseMonthlyPriceInCents || nfsePublicOffer.monthlyPriceInCents;
  const nfseOverage = servicePlan.nfseOverageInCents || nfsePublicOffer.overageInCents;
  return <div className="page-wrap"><Link className="mb-4 inline-flex text-sm font-bold text-brand" href={`/financeiro?mes=${month}`}>← Voltar ao fluxo de caixa</Link><PageHeader eyebrow="Financeiro Pro" title="Comissões, caixa e integrações" description="Operações próprias do cliente, sem tarifas financeiras assumidas pelo Aggenda." />
    <section id="comissoes" className="grid scroll-mt-5 gap-5 xl:grid-cols-2"><article className="panel"><h2 className="text-lg font-extrabold">Regras de comissão</h2><ActionForm action={createCommissionRule} successMessage="Regra criada." className="mt-4 grid gap-3 md:grid-cols-2"><select className="field" name="professionalId" required><option value="">Profissional</option>{professionalsList.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="field" name="serviceId"><option value="">Todos os serviços</option>{servicesList.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="field" name="calculationType"><option value="percentage">Percentual</option><option value="fixed">Valor fixo</option></select><input className="field" name="value" required inputMode="decimal" placeholder="Ex.: 10 (%) ou 25 (R$)" /><button className="primary-button">Criar regra</button></ActionForm><div className="mt-4 divide-y">{rules.map((item) => <p className="py-3 text-sm" key={item.id}><strong>{item.professional}</strong> · {item.service || "Todos os serviços"} · {item.type === "percentage" ? `${item.value / 100}%` : money(item.value)}</p>)}</div></article>
    <article className="panel"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-extrabold">Comissões de {month}</h2><p className="text-sm text-muted">Total {money(commissionTotal)}</p></div><ActionForm action={generateCommissions} successMessage="Comissões calculadas."><input type="hidden" name="competence" value={month} /><button className="secondary-button">Calcular atendimentos concluídos</button></ActionForm></div><div className="mt-4 divide-y">{commissions.map((item) => <div className="flex items-center justify-between gap-3 py-3 text-sm" key={item.id}><span><strong>{item.professional}</strong><br /><span className="text-muted">Base {money(item.base)}</span></span><strong>{money(item.amount)}</strong>{item.status === "pending" ? <ActionForm action={markCommissionPaid} successMessage="Comissão paga."><input type="hidden" name="id" value={item.id} /><button className="secondary-button">Marcar paga</button></ActionForm> : <span className="status-pill">Paga</span>}</div>)}</div></article></section>
    <section id="fechamento-caixa" className="panel mt-5 scroll-mt-5"><h2 className="text-lg font-extrabold">Fechamento de caixa</h2><div className="mt-4 grid gap-5 lg:grid-cols-2"><ActionForm action={openCash} successMessage="Caixa aberto." className="grid gap-3"><select className="field" name="accountId" required><option value="">Conta ou caixa</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input className="field" name="openingBalance" inputMode="decimal" required placeholder="Saldo contado na abertura" /><button className="primary-button">Abrir caixa</button></ActionForm><div className="grid gap-3">{openCashList.map((item) => <ActionForm action={closeCash} successMessage="Caixa fechado." className="rounded-2xl border p-4" key={item.id}><input type="hidden" name="id" value={item.id} /><p className="font-bold">{item.account} · abertura {money(item.opening)}</p><div className="mt-3 flex flex-wrap gap-2"><input className="field flex-1" name="countedBalance" inputMode="decimal" required placeholder="Saldo contado" /><input className="field flex-1" name="notes" placeholder="Observação" /><button className="secondary-button">Fechar e conferir</button></div></ActionForm>)}</div></div></section>
    <section id="conciliacao-ofx" className="panel mt-5 scroll-mt-5"><h2 className="text-lg font-extrabold">Conciliação OFX</h2><p className="text-sm text-muted">O arquivo é processado pelo Aggenda; não há conexão bancária nem mensalidade de Open Finance.</p><ActionForm action={importOfx} successMessage="OFX importado." className="mt-4 flex flex-wrap gap-3"><select className="field max-w-xs" name="accountId" required><option value="">Conta de destino</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input className="field max-w-md" name="file" type="file" accept=".ofx,application/x-ofx" required /><button className="primary-button">Importar OFX</button></ActionForm><div className="mt-4 divide-y">{transactions.map((item) => <div className="grid gap-2 py-3 text-sm lg:grid-cols-[1fr_auto_1fr_auto] lg:items-center" key={item.id}><span><strong>{item.description}</strong><br />{new Date(`${item.occurredOn}T12:00:00Z`).toLocaleDateString("pt-BR")}</span><strong className={item.amountInCents >= 0 ? "text-emerald-700" : "text-red-700"}>{money(item.amountInCents)}</strong><ActionForm action={reconcileOfx} successMessage="Movimento conciliado." className="flex gap-2"><input type="hidden" name="transactionId" value={item.id} /><select className="field" name="entryId" required><option value="">Vincular ao lançamento</option>{pendingEntries.filter((entry) => Math.abs(entry.amount - Math.abs(item.amountInCents)) <= 1).map((entry) => <option key={entry.id} value={entry.id}>{entry.description} · {money(entry.amount)}</option>)}</select><button className="secondary-button">Conciliar</button></ActionForm></div>)}</div></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-2"><article id="cobrancas" className="panel scroll-mt-5"><h2 className="text-lg font-extrabold">Cobranças com conta do cliente</h2><p className="text-sm text-muted">Conecte e valide a conta Asaas da própria empresa. A chave fica criptografada; tarifas, recebimentos e obrigações pertencem ao cliente.</p><ActionForm action={connectAsaasAccount} successMessage="Conta Asaas validada e conectada." className="mt-4 grid gap-3"><select className="field" name="environment"><option value="sandbox">Testes</option><option value="production">Produção</option></select><input className="field" name="credential" type="password" required autoComplete="off" placeholder="Chave API da conta Asaas do cliente" /><button className="primary-button">Conectar e testar conta</button></ActionForm><p className="mt-3 text-xs font-bold">Situação: {integrations.find((item) => item.provider === "asaas")?.status ?? "não configurada"}</p><p className="mt-1 text-xs text-muted">Em produção, o Aggenda também registra um webhook autenticado exclusivo para esta empresa.</p></article>
    <article id="nfse" className="panel scroll-mt-5">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-extrabold">Emissão de NFS-e</h2><p className="mt-1 text-sm text-muted">Ative o serviço, cadastre os dados fiscais e deixe o Aggenda escolher a melhor rota de emissão.</p></div><span className="status-pill">{nfseReady ? "Ativo" : nfseProfile ? "Diagnóstico pendente" : nfseRequested ? "Configuração pendente" : "Não contratado"}</span></div>
      {!nfseIntegration && <div className="mt-5 rounded-2xl border border-brand/20 bg-brand/5 p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-extrabold">Emissor NFS-e Aggenda</p><p className="mt-1 text-sm leading-6 text-muted">Emissão pelo Governo sempre que compatível, com fallback automático pelo parceiro fiscal quando necessário.</p></div><p className="text-2xl font-extrabold text-brand">{money(nfsePublicOffer.monthlyPriceInCents)}<span className="text-sm font-medium text-muted">/mês</span></p></div><div className="mt-4 grid gap-3 rounded-xl border bg-white p-4 text-sm sm:grid-cols-2"><p><strong>{nfsePublicOffer.monthlyLimit} emissões/mês</strong><br /><span className="text-muted">1 CNPJ · sem acúmulo</span></p><p><strong>{money(nfsePublicOffer.overageInCents)} por excedente</strong><br /><span className="text-muted">XML, DANFSe, consulta e cancelamento</span></p><p><strong>Autoconfiguração gratuita</strong><br /><span className="text-muted">Certificado A1 fornecido pelo cliente</span></p><p><strong>Configuração assistida: {money(nfsePublicOffer.assistedSetupInCents)}</strong><br /><span className="text-muted">Cobrança única, se escolhida</span></p></div><p className="mt-3 text-xs text-muted">Disponibilidade confirmada após diagnóstico do município. Integrações extraordinárias exigem orçamento prévio e nunca são cobradas automaticamente.</p><ActionForm action={requestNfseActivation} successMessage="Solicitação de NFS-e recebida." className="mt-4 grid gap-3"><label className="grid gap-2 text-sm font-bold">Implantação<select className="field" name="setupMode" defaultValue="self_service"><option value="self_service">Autoconfiguração · grátis</option><option value="assisted">Configuração assistida · {money(nfsePublicOffer.assistedSetupInCents)}</option></select></label><label className="flex items-start gap-3 rounded-xl border bg-white p-3 text-sm"><input className="mt-1" name="acceptNfseOffer" type="checkbox" required /><span>Li e aceito a mensalidade, franquia e valor excedente apresentados. A cobrança em produção será confirmada antes da ativação.</span></label><button className="primary-button">Solicitar ativação da NFS-e</button></ActionForm></div>}
      {needsFiscalProfile && <div className="mt-5"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm"><p className="font-extrabold text-amber-900">Solicitação recebida</p><p className="mt-1 leading-6 text-amber-800">Cadastre os dados fiscais e o certificado A1. O Aggenda verificará primeiro a emissão direta pelo Governo e usará o parceiro somente quando necessário.</p></div><ActionForm action={saveNfseFiscalProfile} successMessage="Cadastro fiscal salvo com segurança." className="mt-4 grid gap-3 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold">CNPJ<input className="field" name="cnpj" inputMode="numeric" required placeholder="00.000.000/0000-00" /></label><label className="grid gap-2 text-sm font-bold">Inscrição municipal<input className="field" name="municipalRegistration" required /></label><label className="grid gap-2 text-sm font-bold">Código IBGE do município<input className="field" name="municipalityCode" inputMode="numeric" required minLength={7} maxLength={7} placeholder="Ex.: 2927408" /><span className="text-xs font-normal text-muted">Código de 7 dígitos, não o CEP.</span></label><label className="grid gap-2 text-sm font-bold">Regime tributário<select className="field" name="taxRegime" required><option value="simples_nacional">Simples Nacional</option><option value="mei">MEI</option><option value="lucro_presumido">Lucro Presumido</option><option value="lucro_real">Lucro Real</option></select></label><label className="grid gap-2 text-sm font-bold">Ambiente<select className="field" name="environment" defaultValue="sandbox"><option value="sandbox">Homologação (testes)</option><option value="production">Produção</option></select></label><label className="grid gap-2 text-sm font-bold">Certificado digital A1<input className="field" name="certificate" type="file" accept=".pfx,.p12,application/x-pkcs12" required /></label><label className="grid gap-2 text-sm font-bold md:col-span-2">Senha do certificado<input className="field" name="certificatePassword" type="password" required autoComplete="off" /></label><label className="flex items-start gap-3 rounded-xl border p-3 text-sm md:col-span-2"><input className="mt-1" name="partnerFallbackAuthorized" type="checkbox" /><span><strong>Autorizar fallback automático</strong><span className="block text-muted">Se o município não aceitar a API nacional, o Aggenda poderá utilizar o parceiro fiscal. Custos serão informados antes da ativação em produção.</span></span></label><button className="primary-button md:col-span-2">Salvar cadastro fiscal</button></ActionForm></div>}
      {nfseProfile && !nfseReady && <div className="mt-5"><div className="rounded-2xl border p-4 text-sm"><p className="font-extrabold">Cadastro fiscal concluído</p><p className="mt-1 text-muted">Município IBGE {nfseProfile.municipalityCode} · CNPJ final {nfseProfile.cnpj.slice(-4)} · {nfseIntegration?.environment === "production" ? "produção" : "homologação"}</p>{nfseProfile.compatibilityMessage && <p className="mt-2 font-medium">{nfseProfile.compatibilityMessage}</p>}</div><ActionForm action={diagnoseNfseCompatibility} successMessage="Compatibilidade fiscal verificada." className="mt-4"><button className="primary-button">Verificar compatibilidade e definir rota</button></ActionForm></div>}
      {nfseReady && <div className="mt-4 grid gap-3 rounded-2xl border p-4 text-sm sm:grid-cols-3"><p><span className="text-muted">Mensalidade</span><strong className="block text-lg">{money(nfseMonthlyPrice)}</strong></p><p><span className="text-muted">Uso em {month}</span><strong className="block text-lg">{nfseUsage?.value ?? 0} de {nfseMonthlyLimit}</strong></p><p><span className="text-muted">Excedente</span><strong className="block text-lg">{money(nfseOverage)}/nota</strong></p></div>}
      {nfseReady && nfseProfile && <div className="mt-5"><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm"><p className="font-extrabold text-emerald-900">Rota fiscal ativa: {nfseProfile.routingMode === "government" ? "Emissor Público Nacional" : "parceiro fiscal"}</p><p className="mt-1 text-emerald-800">Ambiente: {nfseIntegration?.environment === "production" ? "produção" : "homologação"}. A rota é escolhida automaticamente; o Governo sempre tem prioridade.</p></div><div className="mt-5 rounded-2xl border p-4"><p className="font-extrabold">Registro de contingência</p><p className="mt-1 text-sm text-muted">Use apenas para trazer ao Aggenda uma nota emitida fora do sistema enquanto a transmissão automática está em homologação.</p><ActionForm action={registerFiscalDocument} successMessage="Documento fiscal registrado." className="mt-4 grid gap-3"><label className="grid gap-2 text-sm font-bold">Lançamento financeiro<select className="field" name="financialEntryId"><option value="">Sem lançamento vinculado</option>{pendingEntries.map((entry) => <option key={entry.id} value={entry.id}>{entry.description}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Número da NFS-e<input className="field" name="number" placeholder="Ex.: 000123" /></label><label className="grid gap-2 text-sm font-bold">Valor da nota<input className="field" name="amount" inputMode="decimal" required placeholder="Ex.: 250,00" /></label><label className="grid gap-2 text-sm font-bold">Link de verificação<input className="field" name="verificationUrl" type="url" placeholder="https://..." /></label><button className="secondary-button">Registrar NFS-e já emitida</button></ActionForm></div><p className="mt-3 text-xs text-muted">{documents.length} documento(s) fiscal(is) registrado(s).</p></div>}
    </article></section>
  </div>;
}
