import { and, asc, desc, eq, isNull } from "drizzle-orm";
import Link from "next/link";
import { closeCash, createCommissionRule, generateCommissions, importOfx, markCommissionPaid, openCash, reconcileOfx, registerFiscalDocument, saveClientFinancialIntegration } from "@/actions/financial-operations";
import { ActionForm } from "@/components/action-form";
import { PageHeader } from "@/components/page-header";
import { db } from "@/db";
import { bankImportTransactions, cashClosings, commissionEntries, commissionRules, financialAccounts, financialEntries, fiscalDocuments, organizationFinancialIntegrations, professionals, services } from "@/db/schema";
import { organizationDate } from "@/lib/appointment-safety";
import { requireOrganization } from "@/lib/session";

const money = (value: number) => (value / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
export default async function FinancialOperationsPage({ searchParams }: { searchParams: Promise<{ mes?: string }> }) {
  const { organization } = await requireOrganization(); const query = await searchParams; const current = organizationDate(new Date(), organization.timezone).slice(0, 7); const month = /^\d{4}-\d{2}$/.test(query.mes ?? "") ? query.mes! : current;
  const [professionalsList, servicesList, accounts, rules, commissions, openCashList, transactions, pendingEntries, integrations, documents] = await Promise.all([
    db.select({ id: professionals.id, name: professionals.name }).from(professionals).where(eq(professionals.organizationId, organization.id)).orderBy(asc(professionals.name)),
    db.select({ id: services.id, name: services.name }).from(services).where(eq(services.organizationId, organization.id)).orderBy(asc(services.name)),
    db.select().from(financialAccounts).where(eq(financialAccounts.organizationId, organization.id)).orderBy(asc(financialAccounts.name)),
    db.select({ id: commissionRules.id, professional: professionals.name, service: services.name, type: commissionRules.calculationType, value: commissionRules.value }).from(commissionRules).innerJoin(professionals, eq(professionals.id, commissionRules.professionalId)).leftJoin(services, eq(services.id, commissionRules.serviceId)).where(eq(commissionRules.organizationId, organization.id)),
    db.select({ id: commissionEntries.id, professional: professionals.name, amount: commissionEntries.amountInCents, base: commissionEntries.baseAmountInCents, status: commissionEntries.status }).from(commissionEntries).innerJoin(professionals, eq(professionals.id, commissionEntries.professionalId)).where(and(eq(commissionEntries.organizationId, organization.id), eq(commissionEntries.competence, month))).orderBy(asc(professionals.name)),
    db.select({ id: cashClosings.id, accountId: cashClosings.accountId, account: financialAccounts.name, opening: cashClosings.openingBalanceInCents, openedAt: cashClosings.openedAt }).from(cashClosings).innerJoin(financialAccounts, eq(financialAccounts.id, cashClosings.accountId)).where(and(eq(cashClosings.organizationId, organization.id), isNull(cashClosings.closedAt))),
    db.select().from(bankImportTransactions).where(and(eq(bankImportTransactions.organizationId, organization.id), eq(bankImportTransactions.status, "unmatched"))).orderBy(desc(bankImportTransactions.occurredOn)).limit(30),
    db.select({ id: financialEntries.id, description: financialEntries.description, amount: financialEntries.amountInCents, type: financialEntries.type, dueDate: financialEntries.dueDate }).from(financialEntries).where(and(eq(financialEntries.organizationId, organization.id), eq(financialEntries.status, "pending"))).orderBy(desc(financialEntries.dueDate)).limit(100),
    db.select({ provider: organizationFinancialIntegrations.provider, environment: organizationFinancialIntegrations.environment, status: organizationFinancialIntegrations.status }).from(organizationFinancialIntegrations).where(eq(organizationFinancialIntegrations.organizationId, organization.id)),
    db.select().from(fiscalDocuments).where(eq(fiscalDocuments.organizationId, organization.id)).orderBy(desc(fiscalDocuments.createdAt)).limit(20),
  ]);
  const commissionTotal = commissions.reduce((sum, item) => sum + item.amount, 0);
  return <div className="page-wrap"><Link className="mb-4 inline-flex text-sm font-bold text-brand" href={`/financeiro?mes=${month}`}>← Voltar ao fluxo de caixa</Link><PageHeader eyebrow="Financeiro Pro" title="Comissões, caixa e integrações" description="Operações próprias do cliente, sem tarifas financeiras assumidas pelo Aggenda." />
    <section className="grid gap-5 xl:grid-cols-2"><article className="panel"><h2 className="text-lg font-extrabold">Regras de comissão</h2><ActionForm action={createCommissionRule} successMessage="Regra criada." className="mt-4 grid gap-3 md:grid-cols-2"><select className="field" name="professionalId" required><option value="">Profissional</option>{professionalsList.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="field" name="serviceId"><option value="">Todos os serviços</option>{servicesList.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="field" name="calculationType"><option value="percentage">Percentual</option><option value="fixed">Valor fixo</option></select><input className="field" name="value" required inputMode="decimal" placeholder="Ex.: 10 (%) ou 25 (R$)" /><button className="primary-button">Criar regra</button></ActionForm><div className="mt-4 divide-y">{rules.map((item) => <p className="py-3 text-sm" key={item.id}><strong>{item.professional}</strong> · {item.service || "Todos os serviços"} · {item.type === "percentage" ? `${item.value / 100}%` : money(item.value)}</p>)}</div></article>
    <article className="panel"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-extrabold">Comissões de {month}</h2><p className="text-sm text-muted">Total {money(commissionTotal)}</p></div><ActionForm action={generateCommissions} successMessage="Comissões calculadas."><input type="hidden" name="competence" value={month} /><button className="secondary-button">Calcular atendimentos concluídos</button></ActionForm></div><div className="mt-4 divide-y">{commissions.map((item) => <div className="flex items-center justify-between gap-3 py-3 text-sm" key={item.id}><span><strong>{item.professional}</strong><br /><span className="text-muted">Base {money(item.base)}</span></span><strong>{money(item.amount)}</strong>{item.status === "pending" ? <ActionForm action={markCommissionPaid} successMessage="Comissão paga."><input type="hidden" name="id" value={item.id} /><button className="secondary-button">Marcar paga</button></ActionForm> : <span className="status-pill">Paga</span>}</div>)}</div></article></section>
    <section className="panel mt-5"><h2 className="text-lg font-extrabold">Fechamento de caixa</h2><div className="mt-4 grid gap-5 lg:grid-cols-2"><ActionForm action={openCash} successMessage="Caixa aberto." className="grid gap-3"><select className="field" name="accountId" required><option value="">Conta ou caixa</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input className="field" name="openingBalance" inputMode="decimal" required placeholder="Saldo contado na abertura" /><button className="primary-button">Abrir caixa</button></ActionForm><div className="grid gap-3">{openCashList.map((item) => <ActionForm action={closeCash} successMessage="Caixa fechado." className="rounded-2xl border p-4" key={item.id}><input type="hidden" name="id" value={item.id} /><p className="font-bold">{item.account} · abertura {money(item.opening)}</p><div className="mt-3 flex flex-wrap gap-2"><input className="field flex-1" name="countedBalance" inputMode="decimal" required placeholder="Saldo contado" /><input className="field flex-1" name="notes" placeholder="Observação" /><button className="secondary-button">Fechar e conferir</button></div></ActionForm>)}</div></div></section>
    <section className="panel mt-5"><h2 className="text-lg font-extrabold">Conciliação OFX</h2><p className="text-sm text-muted">O arquivo é processado pelo Aggenda; não há conexão bancária nem mensalidade de Open Finance.</p><ActionForm action={importOfx} successMessage="OFX importado." className="mt-4 flex flex-wrap gap-3"><select className="field max-w-xs" name="accountId" required><option value="">Conta de destino</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input className="field max-w-md" name="file" type="file" accept=".ofx,application/x-ofx" required /><button className="primary-button">Importar OFX</button></ActionForm><div className="mt-4 divide-y">{transactions.map((item) => <div className="grid gap-2 py-3 text-sm lg:grid-cols-[1fr_auto_1fr_auto] lg:items-center" key={item.id}><span><strong>{item.description}</strong><br />{new Date(`${item.occurredOn}T12:00:00Z`).toLocaleDateString("pt-BR")}</span><strong className={item.amountInCents >= 0 ? "text-emerald-700" : "text-red-700"}>{money(item.amountInCents)}</strong><ActionForm action={reconcileOfx} successMessage="Movimento conciliado." className="flex gap-2"><input type="hidden" name="transactionId" value={item.id} /><select className="field" name="entryId" required><option value="">Vincular ao lançamento</option>{pendingEntries.filter((entry) => Math.abs(entry.amount - Math.abs(item.amountInCents)) <= 1).map((entry) => <option key={entry.id} value={entry.id}>{entry.description} · {money(entry.amount)}</option>)}</select><button className="secondary-button">Conciliar</button></ActionForm></div>)}</div></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-2"><article className="panel"><h2 className="text-lg font-extrabold">Cobranças com conta do cliente</h2><p className="text-sm text-muted">Conecte a conta Asaas da própria empresa. Tarifas, recebimentos e obrigações pertencem ao cliente, nunca ao Aggenda.</p><ActionForm action={saveClientFinancialIntegration} successMessage="Conta Asaas configurada." className="mt-4 grid gap-3"><input type="hidden" name="provider" value="asaas" /><select className="field" name="environment"><option value="sandbox">Testes</option><option value="production">Produção</option></select><input className="field" name="credential" type="password" required placeholder="Chave API da conta Asaas do cliente" /><button className="primary-button">Salvar conexão própria</button></ActionForm><p className="mt-3 text-xs font-bold">Situação: {integrations.find((item) => item.provider === "asaas")?.status ?? "não configurada"}</p></article>
    <article className="panel"><h2 className="text-lg font-extrabold">NFS-e BYOK</h2><p className="text-sm text-muted">O cliente fornece a própria credencial do emissor e assume eventuais custos e obrigações fiscais.</p><ActionForm action={saveClientFinancialIntegration} successMessage="Provedor fiscal configurado." className="mt-4 grid gap-3"><input type="hidden" name="provider" value="nfse" /><select className="field" name="environment"><option value="sandbox">Homologação</option><option value="production">Produção</option></select><input className="field" name="credential" type="password" required placeholder="Token do provedor fiscal do cliente" /><button className="secondary-button">Salvar credencial fiscal</button></ActionForm><ActionForm action={registerFiscalDocument} successMessage="Documento fiscal registrado." className="mt-5 grid gap-3"><select className="field" name="financialEntryId"><option value="">Sem lançamento vinculado</option>{pendingEntries.map((entry) => <option key={entry.id} value={entry.id}>{entry.description}</option>)}</select><input className="field" name="number" placeholder="Número da NFS-e" /><input className="field" name="amount" inputMode="decimal" required placeholder="Valor" /><input className="field" name="verificationUrl" type="url" placeholder="URL de verificação" /><button className="secondary-button">Registrar nota emitida</button></ActionForm><p className="mt-3 text-xs text-muted">{documents.length} documento(s) fiscal(is) registrado(s).</p></article></section>
  </div>;
}
