"use client";

import { useState } from "react";

const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

export function ReturnCalculator() {
  const [materials, setMaterials] = useState(80); const [hourCost, setHourCost] = useState(70); const [duration, setDuration] = useState(60); const [commission, setCommission] = useState(15); const [fees, setFees] = useState(4); const [margin, setMargin] = useState(30);
  const directCost = materials + hourCost * duration / 60; const percentage = Math.min(95, commission + fees + margin); const suggestedPrice = directCost / (1 - percentage / 100); const contribution = suggestedPrice - directCost - suggestedPrice * (commission + fees) / 100;
  return <div className="mt-6 grid gap-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><label className="grid gap-2 text-sm font-bold">Insumos (R$)<input className="field" type="number" min="0" value={materials} onChange={(event) => setMaterials(Number(event.target.value))} /></label><label className="grid gap-2 text-sm font-bold">Custo da hora (R$)<input className="field" type="number" min="0" value={hourCost} onChange={(event) => setHourCost(Number(event.target.value))} /></label><label className="grid gap-2 text-sm font-bold">Duração (minutos)<input className="field" type="number" min="1" value={duration} onChange={(event) => setDuration(Number(event.target.value))} /></label><label className="grid gap-2 text-sm font-bold">Comissão (%)<input className="field" type="number" min="0" max="100" value={commission} onChange={(event) => setCommission(Number(event.target.value))} /></label><label className="grid gap-2 text-sm font-bold">Taxas (%)<input className="field" type="number" min="0" max="100" value={fees} onChange={(event) => setFees(Number(event.target.value))} /></label><label className="grid gap-2 text-sm font-bold">Margem desejada (%)<input className="field" type="number" min="0" max="100" value={margin} onChange={(event) => setMargin(Number(event.target.value))} /></label></div><div className="rounded-2xl bg-brand p-6 text-white"><p className="text-sm font-bold text-white/70">Preço sugerido</p><p className="mt-2 text-4xl font-extrabold">{money(Number.isFinite(suggestedPrice) ? suggestedPrice : 0)}</p><p className="mt-2 text-sm">Custo direto {money(directCost)} · contribuição estimada {money(contribution)}</p></div><p className="text-xs text-muted">Estimativa gerencial. Impostos, ociosidade, perdas e custos fixos específicos podem exigir ajustes.</p></div>;
}
